// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inspectz/inspectzpb/inspectz.proto

package inspectzpb

import (
	context "context"
	fmt "fmt"
	kvflowinspectpb "github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/kvflowinspectpb"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("inspectz/inspectzpb/inspectz.proto", fileDescriptor_060b40a990bf0348)
}

var fileDescriptor_060b40a990bf0348 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xbf, 0x4a, 0x03, 0x31,
	0x1c, 0xc7, 0x2f, 0x0e, 0x22, 0x07, 0x82, 0xdc, 0x78, 0x68, 0x86, 0x3e, 0x40, 0x02, 0xba, 0xb8,
	0xb8, 0x58, 0xa9, 0x8a, 0x9b, 0x83, 0x43, 0xb7, 0x24, 0x8d, 0xd7, 0x23, 0x31, 0xbf, 0x98, 0xa4,
	0x29, 0xf8, 0x14, 0x3e, 0x80, 0xab, 0xef, 0xd2, 0xb1, 0x6e, 0x1d, 0xf5, 0xee, 0x45, 0x04, 0xef,
	0x1f, 0x15, 0x27, 0xbb, 0xfd, 0x7e, 0x24, 0xdf, 0xcf, 0xe7, 0x0b, 0x49, 0x3a, 0x2a, 0x8d, 0xb7,
	0x52, 0x84, 0x17, 0xda, 0x0d, 0x96, 0xf7, 0x23, 0xb1, 0x0e, 0x02, 0x64, 0x27, 0x02, 0x84, 0x72,
	0xc0, 0xc4, 0x9c, 0xf4, 0x27, 0xc3, 0xed, 0xfc, 0xb8, 0x00, 0x28, 0xb4, 0xa4, 0xcc, 0x96, 0x94,
	0x19, 0x03, 0x81, 0x85, 0x12, 0x8c, 0x6f, 0xc2, 0xf9, 0x85, 0x8a, 0x54, 0x45, 0x2f, 0x5d, 0x94,
	0x8e, 0xaa, 0xf8, 0xa8, 0x61, 0x29, 0xc0, 0x04, 0x07, 0xba, 0xdd, 0x5a, 0x92, 0xe5, 0xdb, 0x7b,
	0x13, 0x3f, 0xfd, 0xd8, 0x4b, 0x0f, 0x6e, 0x5b, 0x57, 0xf6, 0x8e, 0xd2, 0xa3, 0xbb, 0x87, 0x89,
	0x86, 0xe5, 0xb8, 0x41, 0x68, 0xe9, 0xb2, 0x09, 0x19, 0xea, 0xa9, 0x48, 0x3a, 0x17, 0xd9, 0x72,
	0x91, 0x5f, 0x2e, 0x32, 0x00, 0xee, 0xe5, 0xf3, 0x42, 0xfa, 0x90, 0x5f, 0xef, 0xcc, 0xf1, 0x16,
	0x8c, 0x97, 0xa3, 0x24, 0x7b, 0x43, 0xe9, 0x61, 0xd3, 0xf3, 0x86, 0x99, 0x99, 0x96, 0x3e, 0x1b,
	0xff, 0x0b, 0xde, 0xa6, 0xbb, 0x86, 0x57, 0xbb, 0x41, 0xba, 0x7a, 0x97, 0xd3, 0xd5, 0x17, 0x4e,
	0x56, 0x15, 0x46, 0xeb, 0x0a, 0xa3, 0x4d, 0x85, 0xd1, 0x67, 0x85, 0xd1, 0x6b, 0x8d, 0x93, 0x75,
	0x8d, 0x93, 0x4d, 0x8d, 0x93, 0xe9, 0x79, 0x51, 0x86, 0xf9, 0x82, 0x13, 0x01, 0x4f, 0xb4, 0x77,
	0xce, 0xf8, 0x30, 0x53, 0xab, 0x0a, 0xfa, 0xc7, 0xd7, 0xe1, 0xfb, 0x3f, 0xcf, 0x76, 0xf6, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0xae, 0xd1, 0x1f, 0xa8, 0x58, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InspectzClient is the client API for Inspectz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InspectzClient interface {
	// KVFlowController exposes in-memory state of the node-level
	// kvflowcontrol.Controller. It's housed under /inspectz/kvflowcontroller.
	KVFlowController(ctx context.Context, in *kvflowinspectpb.ControllerRequest, opts ...grpc.CallOption) (*kvflowinspectpb.ControllerResponse, error)
	// KVFlowHandles exposes in-memory state of kvflowcontrol.Handles. It's housed
	// under /inspectz/kvflowhandles.
	KVFlowHandles(ctx context.Context, in *kvflowinspectpb.HandlesRequest, opts ...grpc.CallOption) (*kvflowinspectpb.HandlesResponse, error)
}

type inspectzClient struct {
	cc *grpc.ClientConn
}

func NewInspectzClient(cc *grpc.ClientConn) InspectzClient {
	return &inspectzClient{cc}
}

func (c *inspectzClient) KVFlowController(ctx context.Context, in *kvflowinspectpb.ControllerRequest, opts ...grpc.CallOption) (*kvflowinspectpb.ControllerResponse, error) {
	out := new(kvflowinspectpb.ControllerResponse)
	err := c.cc.Invoke(ctx, "/cockroach.inspectz.inspectzpb.Inspectz/KVFlowController", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inspectzClient) KVFlowHandles(ctx context.Context, in *kvflowinspectpb.HandlesRequest, opts ...grpc.CallOption) (*kvflowinspectpb.HandlesResponse, error) {
	out := new(kvflowinspectpb.HandlesResponse)
	err := c.cc.Invoke(ctx, "/cockroach.inspectz.inspectzpb.Inspectz/KVFlowHandles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InspectzServer is the server API for Inspectz service.
type InspectzServer interface {
	// KVFlowController exposes in-memory state of the node-level
	// kvflowcontrol.Controller. It's housed under /inspectz/kvflowcontroller.
	KVFlowController(context.Context, *kvflowinspectpb.ControllerRequest) (*kvflowinspectpb.ControllerResponse, error)
	// KVFlowHandles exposes in-memory state of kvflowcontrol.Handles. It's housed
	// under /inspectz/kvflowhandles.
	KVFlowHandles(context.Context, *kvflowinspectpb.HandlesRequest) (*kvflowinspectpb.HandlesResponse, error)
}

// UnimplementedInspectzServer can be embedded to have forward compatible implementations.
type UnimplementedInspectzServer struct {
}

func (*UnimplementedInspectzServer) KVFlowController(ctx context.Context, req *kvflowinspectpb.ControllerRequest) (*kvflowinspectpb.ControllerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVFlowController not implemented")
}
func (*UnimplementedInspectzServer) KVFlowHandles(ctx context.Context, req *kvflowinspectpb.HandlesRequest) (*kvflowinspectpb.HandlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVFlowHandles not implemented")
}

func RegisterInspectzServer(s *grpc.Server, srv InspectzServer) {
	s.RegisterService(&_Inspectz_serviceDesc, srv)
}

func _Inspectz_KVFlowController_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kvflowinspectpb.ControllerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectzServer).KVFlowController(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cockroach.inspectz.inspectzpb.Inspectz/KVFlowController",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectzServer).KVFlowController(ctx, req.(*kvflowinspectpb.ControllerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inspectz_KVFlowHandles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kvflowinspectpb.HandlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectzServer).KVFlowHandles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cockroach.inspectz.inspectzpb.Inspectz/KVFlowHandles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectzServer).KVFlowHandles(ctx, req.(*kvflowinspectpb.HandlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Inspectz_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cockroach.inspectz.inspectzpb.Inspectz",
	HandlerType: (*InspectzServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KVFlowController",
			Handler:    _Inspectz_KVFlowController_Handler,
		},
		{
			MethodName: "KVFlowHandles",
			Handler:    _Inspectz_KVFlowHandles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inspectz/inspectzpb/inspectz.proto",
}

