// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: util/log/eventpb/session_events.proto

package eventpb

import (
	fmt "fmt"
	logpb "github.com/cockroachdb/cockroach/pkg/util/log/logpb"
	github_com_cockroachdb_redact "github.com/cockroachdb/redact"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AuthFailReason is the inventory of possible reasons for an
// authentication failure.
type AuthFailReason int32

const (
	// UNKNOWN is reported when the reason is unknown.
	AuthFailReason_UNKNOWN AuthFailReason = 0
	// USER_RETRIEVAL_ERROR occurs when there was an internal error accessing the principals.
	AuthFailReason_USER_RETRIEVAL_ERROR AuthFailReason = 1
	// USER_NOT_FOUND occurs when the principal is unknown.
	AuthFailReason_USER_NOT_FOUND AuthFailReason = 2
	// LOGIN_DISABLED occurs when the user does not have LOGIN privileges.
	AuthFailReason_LOGIN_DISABLED AuthFailReason = 3
	// METHOD_NOT_FOUND occurs when no HBA rule matches or the method does not exist.
	AuthFailReason_METHOD_NOT_FOUND AuthFailReason = 4
	// PRE_HOOK_ERROR occurs when the authentication handshake encountered a protocol error.
	AuthFailReason_PRE_HOOK_ERROR AuthFailReason = 5
	// CREDENTIALS_INVALID occurs when the client-provided credentials were invalid.
	AuthFailReason_CREDENTIALS_INVALID AuthFailReason = 6
	// CREDENTIALS_EXPIRED occur when the credentials provided by the client are expired.
	AuthFailReason_CREDENTIALS_EXPIRED AuthFailReason = 7
	// NO_REPLICATION_ROLEOPTION occurs when the connection requires a replication role option,
	// but the user does not have it.
	AuthFailReason_NO_REPLICATION_ROLEOPTION AuthFailReason = 8
)

var AuthFailReason_name = map[int32]string{
	0: "UNKNOWN",
	1: "USER_RETRIEVAL_ERROR",
	2: "USER_NOT_FOUND",
	3: "LOGIN_DISABLED",
	4: "METHOD_NOT_FOUND",
	5: "PRE_HOOK_ERROR",
	6: "CREDENTIALS_INVALID",
	7: "CREDENTIALS_EXPIRED",
	8: "NO_REPLICATION_ROLEOPTION",
}

var AuthFailReason_value = map[string]int32{
	"UNKNOWN":                   0,
	"USER_RETRIEVAL_ERROR":      1,
	"USER_NOT_FOUND":            2,
	"LOGIN_DISABLED":            3,
	"METHOD_NOT_FOUND":          4,
	"PRE_HOOK_ERROR":            5,
	"CREDENTIALS_INVALID":       6,
	"CREDENTIALS_EXPIRED":       7,
	"NO_REPLICATION_ROLEOPTION": 8,
}

func (x AuthFailReason) String() string {
	return proto.EnumName(AuthFailReason_name, int32(x))
}

func (AuthFailReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aef88ca0e95f42d6, []int{0}
}

// CommonConnectionDetails are payload fields common to all
// connection/session events.
//
// Events of this type are only emitted when the cluster setting
// `server.auth_log.sql_connections.enabled` is set.
type CommonConnectionDetails struct {
	// The instance ID (not tenant ID) of the SQL server where the event was originated.
	InstanceID int32 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:",omitempty"`
	// The network protocol for this connection: tcp4, tcp6, unix, etc.
	Network string `protobuf:"bytes,2,opt,name=network,proto3" json:",omitempty" redact:"nonsensitive"`
	// The remote address of the SQL client. Note that when using a
	// proxy or other intermediate server, this field will contain the
	// address of the intermediate server.
	RemoteAddress string `protobuf:"bytes,3,opt,name=remote_address,json=remoteAddress,proto3" json:",omitempty"`
	// The connection's hex encoded session id.
	SessionID string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:",omitempty" redact:"nonsensitive"`
}

func (m *CommonConnectionDetails) Reset()         { *m = CommonConnectionDetails{} }
func (m *CommonConnectionDetails) String() string { return proto.CompactTextString(m) }
func (*CommonConnectionDetails) ProtoMessage()    {}
func (*CommonConnectionDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef88ca0e95f42d6, []int{0}
}
func (m *CommonConnectionDetails) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommonConnectionDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *CommonConnectionDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonConnectionDetails.Merge(m, src)
}
func (m *CommonConnectionDetails) XXX_Size() int {
	return m.Size()
}
func (m *CommonConnectionDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonConnectionDetails.DiscardUnknown(m)
}

var xxx_messageInfo_CommonConnectionDetails proto.InternalMessageInfo

// CommonConnectionDetails are payload fields common to all
// session events.
//
// Events of this type are only emitted when the cluster setting
// `server.auth_log.sql_connections.enabled` is set.
type CommonSessionDetails struct {
	// The connection type after transport negotiation.
	Transport string `protobuf:"bytes,1,opt,name=transport,proto3" json:",omitempty" redact:"nonsensitive"`
	// The database username the session is for. This username will have
	// undergone case-folding and Unicode normalization.
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:",omitempty"`
	// The original system identity provided by the client, if an identity
	// mapping was used per Host-Based Authentication rules. This may be a
	// GSSAPI or X.509 principal or any other external value, so no
	// specific assumptions should be made about the contents of this
	// field.
	SystemIdentity string `protobuf:"bytes,3,opt,name=system_identity,json=systemIdentity,proto3" json:",omitempty"`
}

func (m *CommonSessionDetails) Reset()         { *m = CommonSessionDetails{} }
func (m *CommonSessionDetails) String() string { return proto.CompactTextString(m) }
func (*CommonSessionDetails) ProtoMessage()    {}
func (*CommonSessionDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef88ca0e95f42d6, []int{1}
}
func (m *CommonSessionDetails) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommonSessionDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *CommonSessionDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonSessionDetails.Merge(m, src)
}
func (m *CommonSessionDetails) XXX_Size() int {
	return m.Size()
}
func (m *CommonSessionDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonSessionDetails.DiscardUnknown(m)
}

var xxx_messageInfo_CommonSessionDetails proto.InternalMessageInfo

// ClientConnectionStart is reported when a client connection
// is established. This is reported even when authentication
// fails, and even for simple cancellation messages.
//
// Events of this type are only emitted when the cluster setting
// `server.auth_log.sql_connections.enabled` is set.
type ClientConnectionStart struct {
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonConnectionDetails  `protobuf:"bytes,2,opt,name=conn,proto3,embedded=conn" json:""`
}

func (m *ClientConnectionStart) Reset()         { *m = ClientConnectionStart{} }
func (m *ClientConnectionStart) String() string { return proto.CompactTextString(m) }
func (*ClientConnectionStart) ProtoMessage()    {}
func (*ClientConnectionStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef88ca0e95f42d6, []int{2}
}
func (m *ClientConnectionStart) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientConnectionStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ClientConnectionStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConnectionStart.Merge(m, src)
}
func (m *ClientConnectionStart) XXX_Size() int {
	return m.Size()
}
func (m *ClientConnectionStart) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConnectionStart.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConnectionStart proto.InternalMessageInfo

// ClientConnectionEnd is reported when a client connection
// is closed. This is reported even when authentication
// fails, and even for simple cancellation messages.
//
// Events of this type are only emitted when the cluster setting
// `server.auth_log.sql_connections.enabled` is set.
type ClientConnectionEnd struct {
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonConnectionDetails  `protobuf:"bytes,2,opt,name=conn,proto3,embedded=conn" json:""`
	// The duration of the connection in nanoseconds.
	Duration int64 `protobuf:"varint,3,opt,name=duration,proto3" json:",omitempty"`
}

func (m *ClientConnectionEnd) Reset()         { *m = ClientConnectionEnd{} }
func (m *ClientConnectionEnd) String() string { return proto.CompactTextString(m) }
func (*ClientConnectionEnd) ProtoMessage()    {}
func (*ClientConnectionEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef88ca0e95f42d6, []int{3}
}
func (m *ClientConnectionEnd) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientConnectionEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ClientConnectionEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConnectionEnd.Merge(m, src)
}
func (m *ClientConnectionEnd) XXX_Size() int {
	return m.Size()
}
func (m *ClientConnectionEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConnectionEnd.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConnectionEnd proto.InternalMessageInfo

// ClientSessionEnd is reported when a client session
// is completed.
//
// Events of this type are only emitted when the cluster setting
// `server.auth_log.sql_sessions.enabled` is set.
type ClientSessionEnd struct {
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonConnectionDetails  `protobuf:"bytes,2,opt,name=conn,proto3,embedded=conn" json:""`
	CommonSessionDetails     `protobuf:"bytes,3,opt,name=session,proto3,embedded=session" json:""`
	// The duration of the connection in nanoseconds.
	Duration int64 `protobuf:"varint,4,opt,name=duration,proto3" json:",omitempty"`
}

func (m *ClientSessionEnd) Reset()         { *m = ClientSessionEnd{} }
func (m *ClientSessionEnd) String() string { return proto.CompactTextString(m) }
func (*ClientSessionEnd) ProtoMessage()    {}
func (*ClientSessionEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef88ca0e95f42d6, []int{4}
}
func (m *ClientSessionEnd) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientSessionEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ClientSessionEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSessionEnd.Merge(m, src)
}
func (m *ClientSessionEnd) XXX_Size() int {
	return m.Size()
}
func (m *ClientSessionEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSessionEnd.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSessionEnd proto.InternalMessageInfo

// ClientAuthenticationFailed is reported when a client session
// did not authenticate successfully.
//
// Events of this type are only emitted when the cluster setting
// `server.auth_log.sql_sessions.enabled` is set.
type ClientAuthenticationFailed struct {
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonConnectionDetails  `protobuf:"bytes,2,opt,name=conn,proto3,embedded=conn" json:""`
	CommonSessionDetails     `protobuf:"bytes,3,opt,name=session,proto3,embedded=session" json:""`
	// The reason for the authentication failure.
	Reason AuthFailReason `protobuf:"varint,4,opt,name=reason,proto3,enum=cockroach.util.log.eventpb.AuthFailReason" json:",includeempty" redact:"nonsensitive"`
	// The detailed error for the authentication failure.
	Detail github_com_cockroachdb_redact.RedactableString `protobuf:"bytes,5,opt,name=detail,proto3,customtype=github.com/cockroachdb/redact.RedactableString" json:",omitempty" redact:"mixed"`
	// The authentication method used.
	Method string `protobuf:"bytes,6,opt,name=method,proto3" json:",omitempty" redact:"nonsensitive"`
}

func (m *ClientAuthenticationFailed) Reset()         { *m = ClientAuthenticationFailed{} }
func (m *ClientAuthenticationFailed) String() string { return proto.CompactTextString(m) }
func (*ClientAuthenticationFailed) ProtoMessage()    {}
func (*ClientAuthenticationFailed) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef88ca0e95f42d6, []int{5}
}
func (m *ClientAuthenticationFailed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientAuthenticationFailed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ClientAuthenticationFailed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientAuthenticationFailed.Merge(m, src)
}
func (m *ClientAuthenticationFailed) XXX_Size() int {
	return m.Size()
}
func (m *ClientAuthenticationFailed) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientAuthenticationFailed.DiscardUnknown(m)
}

var xxx_messageInfo_ClientAuthenticationFailed proto.InternalMessageInfo

// ClientAuthenticationOk is reported when a client session
// was authenticated successfully.
//
// Events of this type are only emitted when the cluster setting
// `server.auth_log.sql_sessions.enabled` is set.
type ClientAuthenticationOk struct {
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonConnectionDetails  `protobuf:"bytes,2,opt,name=conn,proto3,embedded=conn" json:""`
	CommonSessionDetails     `protobuf:"bytes,3,opt,name=session,proto3,embedded=session" json:""`
	// The authentication method used.
	Method string `protobuf:"bytes,4,opt,name=method,proto3" json:",omitempty" redact:"nonsensitive"`
}

func (m *ClientAuthenticationOk) Reset()         { *m = ClientAuthenticationOk{} }
func (m *ClientAuthenticationOk) String() string { return proto.CompactTextString(m) }
func (*ClientAuthenticationOk) ProtoMessage()    {}
func (*ClientAuthenticationOk) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef88ca0e95f42d6, []int{6}
}
func (m *ClientAuthenticationOk) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientAuthenticationOk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ClientAuthenticationOk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientAuthenticationOk.Merge(m, src)
}
func (m *ClientAuthenticationOk) XXX_Size() int {
	return m.Size()
}
func (m *ClientAuthenticationOk) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientAuthenticationOk.DiscardUnknown(m)
}

var xxx_messageInfo_ClientAuthenticationOk proto.InternalMessageInfo

// ClientAuthenticationInfo is reported for intermediate
// steps during the authentication process.
//
// Events of this type are only emitted when the cluster setting
// `server.auth_log.sql_sessions.enabled` is set.
type ClientAuthenticationInfo struct {
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonConnectionDetails  `protobuf:"bytes,2,opt,name=conn,proto3,embedded=conn" json:""`
	CommonSessionDetails     `protobuf:"bytes,3,opt,name=session,proto3,embedded=session" json:""`
	// The authentication method used, once known.
	Method string `protobuf:"bytes,4,opt,name=method,proto3" json:",omitempty" redact:"nonsensitive"`
	// The authentication progress message.
	Info string `protobuf:"bytes,5,opt,name=info,proto3" json:",omitempty"`
}

func (m *ClientAuthenticationInfo) Reset()         { *m = ClientAuthenticationInfo{} }
func (m *ClientAuthenticationInfo) String() string { return proto.CompactTextString(m) }
func (*ClientAuthenticationInfo) ProtoMessage()    {}
func (*ClientAuthenticationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef88ca0e95f42d6, []int{7}
}
func (m *ClientAuthenticationInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientAuthenticationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ClientAuthenticationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientAuthenticationInfo.Merge(m, src)
}
func (m *ClientAuthenticationInfo) XXX_Size() int {
	return m.Size()
}
func (m *ClientAuthenticationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientAuthenticationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientAuthenticationInfo proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cockroach.util.log.eventpb.AuthFailReason", AuthFailReason_name, AuthFailReason_value)
	proto.RegisterType((*CommonConnectionDetails)(nil), "cockroach.util.log.eventpb.CommonConnectionDetails")
	proto.RegisterType((*CommonSessionDetails)(nil), "cockroach.util.log.eventpb.CommonSessionDetails")
	proto.RegisterType((*ClientConnectionStart)(nil), "cockroach.util.log.eventpb.ClientConnectionStart")
	proto.RegisterType((*ClientConnectionEnd)(nil), "cockroach.util.log.eventpb.ClientConnectionEnd")
	proto.RegisterType((*ClientSessionEnd)(nil), "cockroach.util.log.eventpb.ClientSessionEnd")
	proto.RegisterType((*ClientAuthenticationFailed)(nil), "cockroach.util.log.eventpb.ClientAuthenticationFailed")
	proto.RegisterType((*ClientAuthenticationOk)(nil), "cockroach.util.log.eventpb.ClientAuthenticationOk")
	proto.RegisterType((*ClientAuthenticationInfo)(nil), "cockroach.util.log.eventpb.ClientAuthenticationInfo")
}

func init() {
	proto.RegisterFile("util/log/eventpb/session_events.proto", fileDescriptor_aef88ca0e95f42d6)
}

var fileDescriptor_aef88ca0e95f42d6 = []byte{
	// 890 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0xc1, 0x6e, 0xdb, 0x46,
	0x10, 0x15, 0x65, 0x59, 0x8e, 0x47, 0x8d, 0x4a, 0x6c, 0x9c, 0x46, 0x15, 0x5a, 0x31, 0x20, 0xd0,
	0x36, 0x30, 0x02, 0xaa, 0x70, 0x1a, 0x14, 0x28, 0x50, 0x14, 0x92, 0xc8, 0x34, 0x44, 0x54, 0xd2,
	0xa0, 0x64, 0x27, 0xe8, 0x85, 0xa0, 0xc8, 0x8d, 0xbc, 0x30, 0xb9, 0x2b, 0x90, 0xab, 0xb4, 0xfe,
	0x8b, 0xfe, 0x45, 0xff, 0xa1, 0x48, 0xef, 0x3e, 0xfa, 0x68, 0xe4, 0x40, 0xb4, 0x32, 0xd0, 0x83,
	0x8f, 0xfd, 0x80, 0xa2, 0xe0, 0x92, 0xb2, 0x6b, 0xd9, 0xaa, 0x91, 0xf6, 0x14, 0x24, 0x27, 0x2e,
	0x77, 0x66, 0xde, 0xcc, 0x7b, 0x3b, 0x3b, 0x58, 0xf8, 0x64, 0xca, 0x49, 0xd8, 0x0e, 0xd9, 0xb8,
	0x8d, 0x5f, 0x60, 0xca, 0x27, 0xa3, 0x76, 0x82, 0x93, 0x84, 0x30, 0xea, 0x8a, 0xff, 0x44, 0x9b,
	0xc4, 0x8c, 0x33, 0xd4, 0xf4, 0x99, 0xbf, 0x1f, 0x33, 0xcf, 0xdf, 0xd3, 0xb2, 0x00, 0x2d, 0x64,
	0x63, 0xad, 0x08, 0x68, 0x6e, 0x8c, 0xd9, 0x98, 0x09, 0xb7, 0x76, 0xb6, 0xca, 0x23, 0x9a, 0xcd,
	0x33, 0xe0, 0x90, 0x8d, 0x27, 0xa3, 0x1c, 0x3e, 0xb7, 0xa9, 0x3f, 0x97, 0xe1, 0x4e, 0x8f, 0x45,
	0x11, 0xa3, 0x3d, 0x46, 0x29, 0xf6, 0x39, 0x61, 0x54, 0xc7, 0xdc, 0x23, 0x61, 0x82, 0xbe, 0x86,
	0x1a, 0xa1, 0x09, 0xf7, 0xa8, 0x8f, 0x5d, 0x12, 0x34, 0xa4, 0xbb, 0xd2, 0xbd, 0xd5, 0xee, 0x47,
	0xb3, 0x54, 0x01, 0xb3, 0xd8, 0x36, 0xf5, 0xd3, 0x54, 0x81, 0xfb, 0x2c, 0x22, 0x1c, 0x47, 0x13,
	0x7e, 0xe0, 0xc0, 0x3c, 0xc0, 0x0c, 0x50, 0x07, 0xd6, 0x28, 0xe6, 0x3f, 0xb0, 0x78, 0xbf, 0x51,
	0xbe, 0x2b, 0xdd, 0x5b, 0xef, 0x7e, 0x76, 0xd1, 0xf9, 0xcf, 0x54, 0xb9, 0x1d, 0xe3, 0xc0, 0xf3,
	0xf9, 0x57, 0x2a, 0x65, 0x34, 0xc1, 0x34, 0x21, 0x9c, 0xbc, 0xc0, 0xaa, 0x33, 0x8f, 0x43, 0x0f,
	0xa1, 0x1e, 0xe3, 0x88, 0x71, 0xec, 0x7a, 0x41, 0x10, 0xe3, 0x24, 0x69, 0xac, 0x08, 0xa4, 0xfa,
	0x42, 0xda, 0x9b, 0xb9, 0x57, 0x27, 0x77, 0x42, 0x03, 0x80, 0xb9, 0x74, 0x24, 0x68, 0x54, 0x44,
	0xc8, 0x17, 0xb3, 0x54, 0x59, 0x1f, 0xe4, 0xbb, 0x8b, 0x65, 0x2f, 0xaf, 0x64, 0xbd, 0xc0, 0x31,
	0x03, 0xf5, 0x17, 0x09, 0x36, 0x72, 0xa5, 0x0a, 0x94, 0xb9, 0x4c, 0x06, 0xac, 0xf3, 0xd8, 0xa3,
	0xc9, 0x84, 0xc5, 0x5c, 0x88, 0xf4, 0x1a, 0x4c, 0xcf, 0x23, 0x91, 0x0a, 0x95, 0x69, 0x82, 0xe3,
	0x42, 0xab, 0x45, 0x86, 0xc2, 0x86, 0xbe, 0x84, 0xf7, 0x93, 0x83, 0x84, 0xe3, 0xc8, 0x25, 0x01,
	0xa6, 0x9c, 0xf0, 0x83, 0x25, 0x82, 0xd4, 0x73, 0x37, 0xb3, 0xf0, 0x52, 0x5f, 0x4a, 0x70, 0xbb,
	0x17, 0x12, 0x4c, 0xf9, 0xf9, 0x31, 0x0f, 0xb8, 0x17, 0x73, 0xd4, 0x87, 0xaa, 0x2f, 0x58, 0x89,
	0xd2, 0x6b, 0x5b, 0x9f, 0x6a, 0x57, 0xf4, 0x57, 0xce, 0xdb, 0xc8, 0xfa, 0xa6, 0x60, 0xdd, 0x7d,
	0xef, 0x30, 0x55, 0x4a, 0x47, 0xa9, 0x22, 0x9d, 0xa6, 0x4a, 0xc9, 0x29, 0x30, 0xd0, 0x0e, 0x54,
	0x7c, 0x46, 0xa9, 0x20, 0x51, 0xdb, 0x7a, 0xa0, 0x2d, 0xef, 0x55, 0x6d, 0x49, 0xd7, 0x2d, 0x00,
	0x0b, 0x38, 0xf5, 0x0f, 0x09, 0x6e, 0x2d, 0x96, 0x6f, 0xd0, 0xe0, 0x8d, 0x28, 0x1e, 0x6d, 0xc2,
	0x8d, 0x60, 0x1a, 0x7b, 0x99, 0x9b, 0x38, 0xad, 0x95, 0x4b, 0xa7, 0x75, 0x66, 0x57, 0x7f, 0x2d,
	0x83, 0x9c, 0x13, 0x2d, 0x9a, 0xec, 0x8d, 0x61, 0xf9, 0x0c, 0xd6, 0x8a, 0xbb, 0x22, 0x48, 0xd6,
	0xb6, 0x3e, 0xbf, 0x1e, 0xf9, 0xe2, 0x45, 0x5a, 0x80, 0x9d, 0xc3, 0x5d, 0xd0, 0xaf, 0x72, 0x8d,
	0x7e, 0x2f, 0x2b, 0xd0, 0xcc, 0xf5, 0xeb, 0x4c, 0xf9, 0x5e, 0xd6, 0xfc, 0xbe, 0x30, 0x3c, 0xf2,
	0x48, 0x88, 0xdf, 0x7a, 0x25, 0x29, 0x54, 0x63, 0xec, 0x25, 0x85, 0x8e, 0xf5, 0xad, 0xcd, 0x7f,
	0x03, 0xce, 0x04, 0xcc, 0x64, 0x73, 0x44, 0x44, 0x77, 0xf3, 0x34, 0x55, 0x6e, 0xde, 0x27, 0xd4,
	0x0f, 0xa7, 0x01, 0xbe, 0x66, 0xaa, 0x15, 0x59, 0xb2, 0x7c, 0x81, 0xa8, 0xa8, 0xb1, 0x2a, 0xa6,
	0xd4, 0x6e, 0x56, 0xd6, 0xab, 0x54, 0xd1, 0xc6, 0x84, 0xef, 0x4d, 0x47, 0x9a, 0xcf, 0xa2, 0xf6,
	0x59, 0x05, 0xc1, 0xa8, 0x9d, 0xa3, 0x69, 0x8e, 0xf8, 0x78, 0xa3, 0x10, 0x0f, 0x78, 0x4c, 0xe8,
	0xf8, 0xd2, 0x30, 0xad, 0xcf, 0xd3, 0x46, 0xe4, 0x47, 0x1c, 0xa8, 0x4e, 0x91, 0x05, 0x7d, 0x03,
	0xd5, 0x08, 0xf3, 0x3d, 0x16, 0x34, 0xaa, 0xaf, 0x37, 0x86, 0x8b, 0x30, 0xf5, 0xb8, 0x0c, 0x1f,
	0x5c, 0xd5, 0x3e, 0xf6, 0xfe, 0xdb, 0xde, 0x3a, 0xe7, 0xd2, 0x56, 0xfe, 0x9b, 0xb4, 0x7f, 0x95,
	0xa1, 0x71, 0x95, 0xb4, 0x26, 0x7d, 0xce, 0xde, 0x89, 0xfb, 0xff, 0xc4, 0xcd, 0xde, 0x0e, 0x84,
	0x3e, 0x67, 0xc5, 0x35, 0xbb, 0xf4, 0x76, 0xc8, 0x6c, 0x9b, 0xaf, 0x24, 0xa8, 0x5f, 0xbc, 0xd3,
	0xa8, 0x06, 0x6b, 0x3b, 0xd6, 0x13, 0xcb, 0x7e, 0x6a, 0xc9, 0x25, 0xd4, 0x80, 0x8d, 0x9d, 0x81,
	0xe1, 0xb8, 0x8e, 0x31, 0x74, 0x4c, 0x63, 0xb7, 0xd3, 0x77, 0x0d, 0xc7, 0xb1, 0x1d, 0x59, 0x42,
	0x08, 0xea, 0xc2, 0x62, 0xd9, 0x43, 0xf7, 0x91, 0xbd, 0x63, 0xe9, 0x72, 0x39, 0xdb, 0xeb, 0xdb,
	0xdf, 0x9a, 0x96, 0xab, 0x9b, 0x83, 0x4e, 0xb7, 0x6f, 0xe8, 0xf2, 0x0a, 0xda, 0x00, 0xf9, 0x3b,
	0x63, 0xf8, 0xd8, 0xd6, 0xff, 0xe1, 0x59, 0xc9, 0x3c, 0xb7, 0x1d, 0xc3, 0x7d, 0x6c, 0xdb, 0x4f,
	0x0a, 0xc4, 0x55, 0x74, 0x07, 0x6e, 0xf5, 0x1c, 0x43, 0x37, 0xac, 0xa1, 0xd9, 0xe9, 0x0f, 0x5c,
	0xd3, 0xda, 0xed, 0xf4, 0x4d, 0x5d, 0xae, 0x2e, 0x1a, 0x8c, 0x67, 0xdb, 0xa6, 0x63, 0xe8, 0xf2,
	0x1a, 0xfa, 0x18, 0x3e, 0xb4, 0x6c, 0xd7, 0x31, 0xb6, 0xfb, 0x66, 0xaf, 0x33, 0x34, 0x6d, 0xcb,
	0x75, 0xec, 0xbe, 0x61, 0x6f, 0x67, 0x4b, 0xf9, 0x46, 0xf7, 0xe9, 0xe1, 0xef, 0xad, 0xd2, 0xe1,
	0xac, 0x25, 0x1d, 0xcd, 0x5a, 0xd2, 0xf1, 0xac, 0x25, 0xfd, 0x36, 0x6b, 0x49, 0x3f, 0x9d, 0xb4,
	0x4a, 0x47, 0x27, 0xad, 0xd2, 0xf1, 0x49, 0xab, 0xf4, 0xfd, 0xc3, 0x25, 0x33, 0xe7, 0x6c, 0xdd,
	0x9e, 0xec, 0x8f, 0xdb, 0x8b, 0x4f, 0xf0, 0x51, 0x55, 0x3c, 0x93, 0x1f, 0xfc, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0xef, 0x3b, 0x06, 0x0e, 0x9d, 0x0b, 0x00, 0x00,
}

func (m *CommonConnectionDetails) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommonConnectionDetails) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommonConnectionDetails) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SessionID) > 0 {
		i -= len(m.SessionID)
		copy(dAtA[i:], m.SessionID)
		i = encodeVarintSessionEvents(dAtA, i, uint64(len(m.SessionID)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RemoteAddress) > 0 {
		i -= len(m.RemoteAddress)
		copy(dAtA[i:], m.RemoteAddress)
		i = encodeVarintSessionEvents(dAtA, i, uint64(len(m.RemoteAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Network) > 0 {
		i -= len(m.Network)
		copy(dAtA[i:], m.Network)
		i = encodeVarintSessionEvents(dAtA, i, uint64(len(m.Network)))
		i--
		dAtA[i] = 0x12
	}
	if m.InstanceID != 0 {
		i = encodeVarintSessionEvents(dAtA, i, uint64(m.InstanceID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CommonSessionDetails) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommonSessionDetails) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommonSessionDetails) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SystemIdentity) > 0 {
		i -= len(m.SystemIdentity)
		copy(dAtA[i:], m.SystemIdentity)
		i = encodeVarintSessionEvents(dAtA, i, uint64(len(m.SystemIdentity)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.User) > 0 {
		i -= len(m.User)
		copy(dAtA[i:], m.User)
		i = encodeVarintSessionEvents(dAtA, i, uint64(len(m.User)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Transport) > 0 {
		i -= len(m.Transport)
		copy(dAtA[i:], m.Transport)
		i = encodeVarintSessionEvents(dAtA, i, uint64(len(m.Transport)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ClientConnectionStart) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientConnectionStart) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientConnectionStart) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CommonConnectionDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ClientConnectionEnd) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientConnectionEnd) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientConnectionEnd) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Duration != 0 {
		i = encodeVarintSessionEvents(dAtA, i, uint64(m.Duration))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.CommonConnectionDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ClientSessionEnd) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientSessionEnd) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientSessionEnd) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Duration != 0 {
		i = encodeVarintSessionEvents(dAtA, i, uint64(m.Duration))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.CommonSessionDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.CommonConnectionDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ClientAuthenticationFailed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientAuthenticationFailed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientAuthenticationFailed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Method) > 0 {
		i -= len(m.Method)
		copy(dAtA[i:], m.Method)
		i = encodeVarintSessionEvents(dAtA, i, uint64(len(m.Method)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Detail) > 0 {
		i -= len(m.Detail)
		copy(dAtA[i:], m.Detail)
		i = encodeVarintSessionEvents(dAtA, i, uint64(len(m.Detail)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Reason != 0 {
		i = encodeVarintSessionEvents(dAtA, i, uint64(m.Reason))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.CommonSessionDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.CommonConnectionDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ClientAuthenticationOk) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientAuthenticationOk) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientAuthenticationOk) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Method) > 0 {
		i -= len(m.Method)
		copy(dAtA[i:], m.Method)
		i = encodeVarintSessionEvents(dAtA, i, uint64(len(m.Method)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.CommonSessionDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.CommonConnectionDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ClientAuthenticationInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientAuthenticationInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientAuthenticationInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintSessionEvents(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Method) > 0 {
		i -= len(m.Method)
		copy(dAtA[i:], m.Method)
		i = encodeVarintSessionEvents(dAtA, i, uint64(len(m.Method)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.CommonSessionDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.CommonConnectionDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintSessionEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovSessionEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CommonConnectionDetails) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.InstanceID != 0 {
		n += 1 + sovSessionEvents(uint64(m.InstanceID))
	}
	l = len(m.Network)
	if l > 0 {
		n += 1 + l + sovSessionEvents(uint64(l))
	}
	l = len(m.RemoteAddress)
	if l > 0 {
		n += 1 + l + sovSessionEvents(uint64(l))
	}
	l = len(m.SessionID)
	if l > 0 {
		n += 1 + l + sovSessionEvents(uint64(l))
	}
	return n
}

func (m *CommonSessionDetails) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Transport)
	if l > 0 {
		n += 1 + l + sovSessionEvents(uint64(l))
	}
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovSessionEvents(uint64(l))
	}
	l = len(m.SystemIdentity)
	if l > 0 {
		n += 1 + l + sovSessionEvents(uint64(l))
	}
	return n
}

func (m *ClientConnectionStart) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	l = m.CommonConnectionDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	return n
}

func (m *ClientConnectionEnd) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	l = m.CommonConnectionDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	if m.Duration != 0 {
		n += 1 + sovSessionEvents(uint64(m.Duration))
	}
	return n
}

func (m *ClientSessionEnd) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	l = m.CommonConnectionDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	l = m.CommonSessionDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	if m.Duration != 0 {
		n += 1 + sovSessionEvents(uint64(m.Duration))
	}
	return n
}

func (m *ClientAuthenticationFailed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	l = m.CommonConnectionDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	l = m.CommonSessionDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	if m.Reason != 0 {
		n += 1 + sovSessionEvents(uint64(m.Reason))
	}
	l = len(m.Detail)
	if l > 0 {
		n += 1 + l + sovSessionEvents(uint64(l))
	}
	l = len(m.Method)
	if l > 0 {
		n += 1 + l + sovSessionEvents(uint64(l))
	}
	return n
}

func (m *ClientAuthenticationOk) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	l = m.CommonConnectionDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	l = m.CommonSessionDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	l = len(m.Method)
	if l > 0 {
		n += 1 + l + sovSessionEvents(uint64(l))
	}
	return n
}

func (m *ClientAuthenticationInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	l = m.CommonConnectionDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	l = m.CommonSessionDetails.Size()
	n += 1 + l + sovSessionEvents(uint64(l))
	l = len(m.Method)
	if l > 0 {
		n += 1 + l + sovSessionEvents(uint64(l))
	}
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovSessionEvents(uint64(l))
	}
	return n
}

func sovSessionEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSessionEvents(x uint64) (n int) {
	return sovSessionEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CommonConnectionDetails) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessionEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommonConnectionDetails: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommonConnectionDetails: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstanceID", wireType)
			}
			m.InstanceID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InstanceID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Network", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Network = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoteAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSessionEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CommonSessionDetails) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessionEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommonSessionDetails: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommonSessionDetails: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transport", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transport = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SystemIdentity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SystemIdentity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSessionEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientConnectionStart) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessionEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientConnectionStart: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientConnectionStart: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonConnectionDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonConnectionDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSessionEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientConnectionEnd) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessionEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientConnectionEnd: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientConnectionEnd: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonConnectionDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonConnectionDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSessionEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientSessionEnd) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessionEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientSessionEnd: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientSessionEnd: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonConnectionDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonConnectionDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonSessionDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonSessionDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSessionEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientAuthenticationFailed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessionEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientAuthenticationFailed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientAuthenticationFailed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonConnectionDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonConnectionDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonSessionDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonSessionDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			m.Reason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reason |= AuthFailReason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Detail", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Detail = github_com_cockroachdb_redact.RedactableString(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Method = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSessionEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientAuthenticationOk) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessionEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientAuthenticationOk: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientAuthenticationOk: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonConnectionDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonConnectionDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonSessionDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonSessionDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Method = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSessionEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientAuthenticationInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessionEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientAuthenticationInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientAuthenticationInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonConnectionDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonConnectionDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonSessionDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonSessionDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Method = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSessionEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessionEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSessionEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSessionEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSessionEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSessionEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSessionEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSessionEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSessionEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSessionEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSessionEvents = fmt.Errorf("proto: unexpected end of group")
)

