# See https://bors.tech/documentation/ for configuration details.

# List of commit statuses that must pass on the merge commit before it is
# pushed to master.
#
# This is left at being compile only as a rough heuristic to detect merge-skew.
# We don't bother running/waiting on the full CI for merge commits.
status = ["Compile Builds (Unit Tests)"]

# List of commit statuses that must pass on the PR commit when it is r+-ed.
pr_status = ["license/cla", "GitHub CI (Cockroach)"]

# List of PR labels that may not be attached to a PR when it is r+-ed.
block_labels = ["do-not-merge"]

# Number of seconds from when a merge commit is created to when its statuses
# must pass.
#
# Set to 4 hours
timeout_sec = 14400

[committer]
name = "craig[bot]"
email = "bors@cockroachlabs.com"
