// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sql/sqlstats/insights/insights.proto

package insights

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	github_com_cockroachdb_cockroach_pkg_sql_appstatspb "github.com/cockroachdb/cockroach/pkg/sql/appstatspb"
	github_com_cockroachdb_cockroach_pkg_sql_clusterunique "github.com/cockroachdb/cockroach/pkg/sql/clusterunique"
	github_com_cockroachdb_cockroach_pkg_util_uuid "github.com/cockroachdb/cockroach/pkg/util/uuid"
	github_com_cockroachdb_redact "github.com/cockroachdb/redact"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Problem int32

const (
	// This statement execution was not itself problematic, but it happened in
	// the same transaction as another problematic statement.
	Problem_None Problem = 0
	// This statement execution was slow, either above a fixed latency threshold
	// or detected as an anomaly.
	Problem_SlowExecution Problem = 1
	// This statement execution failed completely, due to contention, resource
	// saturation, or syntax errors.
	Problem_FailedExecution Problem = 2
)

var Problem_name = map[int32]string{
	0: "None",
	1: "SlowExecution",
	2: "FailedExecution",
}

var Problem_value = map[string]int32{
	"None":            0,
	"SlowExecution":   1,
	"FailedExecution": 2,
}

func (x Problem) String() string {
	return proto.EnumName(Problem_name, int32(x))
}

func (Problem) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1905fa99396732c4, []int{0}
}

type Cause int32

const (
	// We have not identified specific reasons why this statement was slow.
	// We will not explicitly use this zero value; it is here defensively.
	Cause_Unset Cause = 0
	// This statement was slow because we picked the wrong plan, possibly due to
	// outdated statistics, the statement using different literals or search
	// conditions, or a change in the database schema.
	Cause_PlanRegression Cause = 1
	// This statement was slow because a good plan was not available, whether
	// due to outdated statistics or missing indexes.
	Cause_SuboptimalPlan Cause = 2
	// This statement was slow because of contention.
	Cause_HighContention Cause = 3
	// This statement was slow because of being retried multiple times, again due
	// to contention. The "high" threshold may be configured by the
	// `sql.insights.high_retry_count.threshold` cluster setting.
	Cause_HighRetryCount Cause = 4
)

var Cause_name = map[int32]string{
	0: "Unset",
	1: "PlanRegression",
	2: "SuboptimalPlan",
	3: "HighContention",
	4: "HighRetryCount",
}

var Cause_value = map[string]int32{
	"Unset":          0,
	"PlanRegression": 1,
	"SuboptimalPlan": 2,
	"HighContention": 3,
	"HighRetryCount": 4,
}

func (x Cause) String() string {
	return proto.EnumName(Cause_name, int32(x))
}

func (Cause) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1905fa99396732c4, []int{1}
}

// TODO(gtr): Implement "Cancelled" status for transaction insights.
type Transaction_Status int32

const (
	Transaction_Completed Transaction_Status = 0
	Transaction_Failed    Transaction_Status = 1
)

var Transaction_Status_name = map[int32]string{
	0: "Completed",
	1: "Failed",
}

var Transaction_Status_value = map[string]int32{
	"Completed": 0,
	"Failed":    1,
}

func (x Transaction_Status) String() string {
	return proto.EnumName(Transaction_Status_name, int32(x))
}

func (Transaction_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1905fa99396732c4, []int{1, 0}
}

type Statement_Status int32

const (
	Statement_Completed Statement_Status = 0
	Statement_Failed    Statement_Status = 1
)

var Statement_Status_name = map[int32]string{
	0: "Completed",
	1: "Failed",
}

var Statement_Status_value = map[string]int32{
	"Completed": 0,
	"Failed":    1,
}

func (x Statement_Status) String() string {
	return proto.EnumName(Statement_Status_name, int32(x))
}

func (Statement_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1905fa99396732c4, []int{2, 0}
}

type Session struct {
	ID github_com_cockroachdb_cockroach_pkg_sql_clusterunique.ID `protobuf:"bytes,1,opt,name=id,proto3,customtype=github.com/cockroachdb/cockroach/pkg/sql/clusterunique.ID" json:"id"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_1905fa99396732c4, []int{0}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return m.Size()
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

type Transaction struct {
	ID               github_com_cockroachdb_cockroach_pkg_util_uuid.UUID                          `protobuf:"bytes,1,opt,name=id,proto3,customtype=github.com/cockroachdb/cockroach/pkg/util/uuid.UUID" json:"id"`
	FingerprintID    github_com_cockroachdb_cockroach_pkg_sql_appstatspb.TransactionFingerprintID `protobuf:"varint,2,opt,name=fingerprint_id,json=fingerprintId,proto3,customtype=github.com/cockroachdb/cockroach/pkg/sql/appstatspb.TransactionFingerprintID" json:"fingerprint_id"`
	UserPriority     string                                                                       `protobuf:"bytes,3,opt,name=user_priority,json=userPriority,proto3" json:"user_priority,omitempty"`
	ImplicitTxn      bool                                                                         `protobuf:"varint,4,opt,name=implicit_txn,json=implicitTxn,proto3" json:"implicit_txn,omitempty"`
	Contention       *time.Duration                                                               `protobuf:"bytes,5,opt,name=contention,proto3,stdduration" json:"contention,omitempty"`
	StartTime        time.Time                                                                    `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time"`
	EndTime          time.Time                                                                    `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time"`
	User             string                                                                       `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	ApplicationName  string                                                                       `protobuf:"bytes,9,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	RowsRead         int64                                                                        `protobuf:"varint,10,opt,name=rows_read,json=rowsRead,proto3" json:"rows_read,omitempty"`
	RowsWritten      int64                                                                        `protobuf:"varint,11,opt,name=rows_written,json=rowsWritten,proto3" json:"rows_written,omitempty"`
	RetryCount       int64                                                                        `protobuf:"varint,12,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	AutoRetryReason  string                                                                       `protobuf:"bytes,13,opt,name=auto_retry_reason,json=autoRetryReason,proto3" json:"auto_retry_reason,omitempty"`
	Problems         []Problem                                                                    `protobuf:"varint,14,rep,packed,name=problems,proto3,enum=cockroach.sql.insights.Problem" json:"problems,omitempty"`
	Causes           []Cause                                                                      `protobuf:"varint,15,rep,packed,name=causes,proto3,enum=cockroach.sql.insights.Cause" json:"causes,omitempty"`
	StmtExecutionIDs []github_com_cockroachdb_cockroach_pkg_sql_clusterunique.ID                  `protobuf:"bytes,16,rep,name=stmt_execution_ids,json=stmtExecutionIds,proto3,customtype=github.com/cockroachdb/cockroach/pkg/sql/clusterunique.ID" json:"stmt_execution_ids,omitempty"`
	CPUSQLNanos      int64                                                                        `protobuf:"varint,17,opt,name=cpu_sql_nanos,json=cpuSqlNanos,proto3" json:"cpu_sql_nanos,omitempty"`
	// The error code of the last failed statement in the transaction.
	LastErrorCode string `protobuf:"bytes,18,opt,name=last_error_code,json=lastErrorCode,proto3" json:"last_error_code,omitempty"`
	// The error message of the last failed statement in the transaction.
	LastErrorMsg github_com_cockroachdb_redact.RedactableString `protobuf:"bytes,20,opt,name=last_error_msg,json=lastErrorMsg,proto3,customtype=github.com/cockroachdb/redact.RedactableString" json:"last_error_msg"`
	Status       Transaction_Status                             `protobuf:"varint,19,opt,name=status,proto3,enum=cockroach.sql.insights.Transaction_Status" json:"status,omitempty"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_1905fa99396732c4, []int{1}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return m.Size()
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

type Statement struct {
	ID               github_com_cockroachdb_cockroach_pkg_sql_clusterunique.ID             `protobuf:"bytes,1,opt,name=id,proto3,customtype=github.com/cockroachdb/cockroach/pkg/sql/clusterunique.ID" json:"id"`
	FingerprintID    github_com_cockroachdb_cockroach_pkg_sql_appstatspb.StmtFingerprintID `protobuf:"varint,2,opt,name=fingerprint_id,json=fingerprintId,proto3,casttype=github.com/cockroachdb/cockroach/pkg/sql/appstatspb.StmtFingerprintID" json:"fingerprint_id,omitempty"`
	LatencyInSeconds float64                                                               `protobuf:"fixed64,3,opt,name=latency_in_seconds,json=latencyInSeconds,proto3" json:"latency_in_seconds,omitempty"`
	Query            string                                                                `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Status           Statement_Status                                                      `protobuf:"varint,5,opt,name=status,proto3,enum=cockroach.sql.insights.Statement_Status" json:"status,omitempty"`
	StartTime        time.Time                                                             `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time"`
	EndTime          time.Time                                                             `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time"`
	FullScan         bool                                                                  `protobuf:"varint,8,opt,name=full_scan,json=fullScan,proto3" json:"full_scan,omitempty"`
	Database         string                                                                `protobuf:"bytes,11,opt,name=database,proto3" json:"database,omitempty"`
	PlanGist         string                                                                `protobuf:"bytes,12,opt,name=plan_gist,json=planGist,proto3" json:"plan_gist,omitempty"`
	RowsRead         int64                                                                 `protobuf:"varint,13,opt,name=rows_read,json=rowsRead,proto3" json:"rows_read,omitempty"`
	RowsWritten      int64                                                                 `protobuf:"varint,14,opt,name=rows_written,json=rowsWritten,proto3" json:"rows_written,omitempty"`
	Retries          int64                                                                 `protobuf:"varint,15,opt,name=retries,proto3" json:"retries,omitempty"`
	AutoRetryReason  string                                                                `protobuf:"bytes,16,opt,name=auto_retry_reason,json=autoRetryReason,proto3" json:"auto_retry_reason,omitempty"`
	// Nodes is the ordered list of nodes ids on which the statement was executed.
	Nodes                []int64        `protobuf:"varint,17,rep,packed,name=nodes,proto3" json:"nodes,omitempty"`
	Contention           *time.Duration `protobuf:"bytes,18,opt,name=contention,proto3,stdduration" json:"contention,omitempty"`
	IndexRecommendations []string       `protobuf:"bytes,19,rep,name=index_recommendations,json=indexRecommendations,proto3" json:"index_recommendations,omitempty"`
	Problem              Problem        `protobuf:"varint,21,opt,name=problem,proto3,enum=cockroach.sql.insights.Problem" json:"problem,omitempty"`
	Causes               []Cause        `protobuf:"varint,22,rep,packed,name=causes,proto3,enum=cockroach.sql.insights.Cause" json:"causes,omitempty"`
	CPUSQLNanos          int64          `protobuf:"varint,23,opt,name=cpu_sql_nanos,json=cpuSqlNanos,proto3" json:"cpu_sql_nanos,omitempty"`
	// The most recent error code experienced by this statement.
	ErrorCode string `protobuf:"bytes,24,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// The most recent error experienced by this statement.
	ErrorMsg github_com_cockroachdb_redact.RedactableString `protobuf:"bytes,25,opt,name=error_msg,json=errorMsg,proto3,customtype=github.com/cockroachdb/redact.RedactableString" json:"error_msg"`
}

func (m *Statement) Reset()         { *m = Statement{} }
func (m *Statement) String() string { return proto.CompactTextString(m) }
func (*Statement) ProtoMessage()    {}
func (*Statement) Descriptor() ([]byte, []int) {
	return fileDescriptor_1905fa99396732c4, []int{2}
}
func (m *Statement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Statement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Statement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statement.Merge(m, src)
}
func (m *Statement) XXX_Size() int {
	return m.Size()
}
func (m *Statement) XXX_DiscardUnknown() {
	xxx_messageInfo_Statement.DiscardUnknown(m)
}

var xxx_messageInfo_Statement proto.InternalMessageInfo

type Insight struct {
	Session     Session      `protobuf:"bytes,1,opt,name=session,proto3" json:"session"`
	Transaction *Transaction `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Statements  []*Statement `protobuf:"bytes,6,rep,name=statements,proto3" json:"statements,omitempty"`
	// This field is deprecated, but we have to keep it around for 22.2
	// backwards compatibility. 22.2 actually expects this as non-null
	// when generating the exec insights virtual table. Removing this will
	// cause a nil pointer deref on versions <= 22.2.6.
	// TODO: Move these fields to 'reserved' at 23.2.
	Statement *Statement `protobuf:"bytes,3,opt,name=statement,proto3" json:"statement,omitempty"`
}

func (m *Insight) Reset()         { *m = Insight{} }
func (m *Insight) String() string { return proto.CompactTextString(m) }
func (*Insight) ProtoMessage()    {}
func (*Insight) Descriptor() ([]byte, []int) {
	return fileDescriptor_1905fa99396732c4, []int{3}
}
func (m *Insight) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Insight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Insight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Insight.Merge(m, src)
}
func (m *Insight) XXX_Size() int {
	return m.Size()
}
func (m *Insight) XXX_DiscardUnknown() {
	xxx_messageInfo_Insight.DiscardUnknown(m)
}

var xxx_messageInfo_Insight proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cockroach.sql.insights.Problem", Problem_name, Problem_value)
	proto.RegisterEnum("cockroach.sql.insights.Cause", Cause_name, Cause_value)
	proto.RegisterEnum("cockroach.sql.insights.Transaction_Status", Transaction_Status_name, Transaction_Status_value)
	proto.RegisterEnum("cockroach.sql.insights.Statement_Status", Statement_Status_name, Statement_Status_value)
	proto.RegisterType((*Session)(nil), "cockroach.sql.insights.Session")
	proto.RegisterType((*Transaction)(nil), "cockroach.sql.insights.Transaction")
	proto.RegisterType((*Statement)(nil), "cockroach.sql.insights.Statement")
	proto.RegisterType((*Insight)(nil), "cockroach.sql.insights.Insight")
}

func init() {
	proto.RegisterFile("sql/sqlstats/insights/insights.proto", fileDescriptor_1905fa99396732c4)
}

var fileDescriptor_1905fa99396732c4 = []byte{
	// 1308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x97, 0x4f, 0x6f, 0xdb, 0xb6,
	0x1b, 0xc7, 0xad, 0xf8, 0x9f, 0x44, 0xc7, 0x89, 0xca, 0xa6, 0xfd, 0xa9, 0x29, 0x6a, 0xbb, 0xe9,
	0x0f, 0x83, 0x17, 0x0c, 0x32, 0x90, 0x60, 0x03, 0xba, 0x1e, 0xb2, 0x3a, 0x49, 0xbb, 0x04, 0x5d,
	0x91, 0xd2, 0x0d, 0x0a, 0x14, 0x05, 0x04, 0x5a, 0x62, 0x15, 0xa2, 0x12, 0xa9, 0x88, 0x14, 0x9a,
	0x9c, 0x86, 0xdd, 0x77, 0xe8, 0x71, 0xd7, 0xbd, 0x81, 0xbd, 0x8e, 0x1e, 0x7b, 0x2c, 0x76, 0xc8,
	0xb6, 0xe4, 0x5d, 0xec, 0x34, 0x90, 0x92, 0x1d, 0xa7, 0x69, 0x56, 0x77, 0xc5, 0x80, 0x9d, 0x2c,
	0x7e, 0x9f, 0x3f, 0x24, 0x1f, 0xf2, 0xf9, 0x48, 0x06, 0xff, 0x17, 0xfb, 0x51, 0x4f, 0xec, 0x47,
	0x42, 0x62, 0x29, 0x7a, 0x94, 0x09, 0x1a, 0xee, 0x4d, 0x3c, 0xb8, 0x49, 0xca, 0x25, 0x87, 0x57,
	0x7d, 0xee, 0xbf, 0x48, 0x39, 0xf6, 0xf7, 0x5c, 0xb1, 0x1f, 0xb9, 0x23, 0xeb, 0xe2, 0x42, 0xc8,
	0x43, 0xae, 0x5d, 0x7a, 0xea, 0x29, 0xf7, 0x5e, 0x6c, 0x87, 0x9c, 0x87, 0x11, 0xe9, 0xe9, 0xd1,
	0x30, 0x7b, 0xde, 0x93, 0x34, 0x26, 0x42, 0xe2, 0x38, 0x29, 0x1c, 0x5a, 0xef, 0x3a, 0x04, 0x59,
	0x8a, 0x25, 0xe5, 0x2c, 0xb7, 0x2f, 0x0d, 0x41, 0x7d, 0x40, 0x84, 0xa0, 0x9c, 0xc1, 0x27, 0x60,
	0x86, 0x06, 0x8e, 0xd1, 0x31, 0xba, 0xb3, 0xfd, 0xfb, 0xaf, 0x8f, 0xda, 0xa5, 0x5f, 0x8f, 0xda,
	0xb7, 0x43, 0x2a, 0xf7, 0xb2, 0xa1, 0xeb, 0xf3, 0xb8, 0x37, 0x5e, 0x58, 0x30, 0x3c, 0x7d, 0xee,
	0x25, 0x2f, 0x42, 0xb5, 0xa9, 0x9e, 0x1f, 0x65, 0x42, 0x92, 0x34, 0x63, 0x74, 0x3f, 0x23, 0xee,
	0xd6, 0xc6, 0xf1, 0x51, 0x7b, 0x66, 0x6b, 0x03, 0xcd, 0xd0, 0x60, 0xe9, 0xc4, 0x02, 0x8d, 0xc7,
	0x29, 0x66, 0x02, 0xfb, 0x6a, 0x66, 0xf8, 0x68, 0x62, 0xa2, 0xbb, 0xc5, 0x44, 0xab, 0x53, 0x4d,
	0x94, 0x49, 0x1a, 0xf5, 0xb2, 0x8c, 0x06, 0xee, 0xee, 0xee, 0xe4, 0x14, 0xf0, 0x47, 0x03, 0xcc,
	0x3d, 0xa7, 0x2c, 0x24, 0x69, 0x92, 0x52, 0x26, 0x3d, 0x1a, 0x38, 0x33, 0x1d, 0xa3, 0x5b, 0xe9,
	0x93, 0x22, 0xff, 0x83, 0xa9, 0x37, 0x82, 0x93, 0x44, 0x9f, 0x50, 0x32, 0x74, 0x27, 0x16, 0x7d,
	0xef, 0x34, 0xb9, 0x9e, 0xb8, 0x79, 0x46, 0x40, 0xcd, 0x89, 0xc9, 0xb7, 0x02, 0x78, 0x0b, 0x34,
	0x33, 0x41, 0x52, 0x2f, 0x49, 0x29, 0x4f, 0xa9, 0x3c, 0x74, 0xca, 0x1d, 0xa3, 0x6b, 0xa1, 0x59,
	0x25, 0xee, 0x14, 0x1a, 0xbc, 0x09, 0x66, 0x69, 0x9c, 0x44, 0xd4, 0xa7, 0xd2, 0x93, 0x07, 0xcc,
	0xa9, 0x74, 0x8c, 0xae, 0x89, 0x1a, 0x23, 0xed, 0xf1, 0x01, 0x83, 0x6b, 0x00, 0xf8, 0x9c, 0x49,
	0xc2, 0xd4, 0x12, 0x9c, 0x6a, 0xc7, 0xe8, 0x36, 0x56, 0xae, 0xb9, 0xf9, 0x91, 0xba, 0xa3, 0x23,
	0x75, 0x37, 0x8a, 0x23, 0xed, 0x57, 0x7e, 0xfa, 0xad, 0x6d, 0xa0, 0x89, 0x10, 0xb8, 0x0e, 0x80,
	0x90, 0x38, 0x95, 0x9e, 0xba, 0x17, 0x4e, 0x4d, 0x27, 0x58, 0x3c, 0x97, 0xe0, 0xf1, 0xe8, 0xd2,
	0xf4, 0x4d, 0x55, 0xae, 0x57, 0x2a, 0x8b, 0xa5, 0xe3, 0x94, 0x05, 0xae, 0x01, 0x93, 0xb0, 0x20,
	0x4f, 0x51, 0xff, 0x88, 0x14, 0x75, 0xc2, 0x02, 0x9d, 0x00, 0x82, 0x8a, 0xda, 0xb9, 0x63, 0xea,
	0x2a, 0xe8, 0x67, 0xf8, 0x39, 0xb0, 0x71, 0xa2, 0x76, 0xaa, 0x97, 0xee, 0x31, 0x1c, 0x13, 0xc7,
	0xd2, 0xf6, 0xf9, 0x09, 0xfd, 0x21, 0x8e, 0x09, 0xbc, 0x0e, 0xac, 0x94, 0xbf, 0x14, 0x5e, 0x4a,
	0x70, 0xe0, 0x80, 0x8e, 0xd1, 0x2d, 0x23, 0x53, 0x09, 0x88, 0xe0, 0x40, 0x55, 0x51, 0x1b, 0x5f,
	0xa6, 0x54, 0x4a, 0xc2, 0x9c, 0x86, 0xb6, 0x37, 0x94, 0xf6, 0x24, 0x97, 0x60, 0x1b, 0x34, 0x52,
	0x22, 0xd3, 0x43, 0xcf, 0xe7, 0x19, 0x93, 0xce, 0xac, 0xf6, 0x00, 0x5a, 0x5a, 0x57, 0x0a, 0x5c,
	0x06, 0x97, 0x70, 0x26, 0xb9, 0x97, 0x7b, 0xa5, 0x04, 0x0b, 0xce, 0x9c, 0x66, 0xb1, 0x98, 0x4c,
	0x72, 0xa4, 0x74, 0xa4, 0x65, 0x78, 0x07, 0x98, 0x49, 0xca, 0x87, 0x11, 0x89, 0x85, 0x33, 0xd7,
	0x29, 0x77, 0xe7, 0x56, 0xda, 0xee, 0xfb, 0x5b, 0xd6, 0xdd, 0xc9, 0xfd, 0xd0, 0x38, 0x00, 0x7e,
	0x09, 0x6a, 0x3e, 0xce, 0x04, 0x11, 0xce, 0xbc, 0x0e, 0xbd, 0x71, 0x51, 0xe8, 0xba, 0xf2, 0x42,
	0x85, 0x33, 0xfc, 0x1e, 0x40, 0x21, 0x63, 0xe9, 0x91, 0x03, 0xe2, 0x67, 0xba, 0x5c, 0x34, 0x10,
	0x8e, 0xdd, 0x29, 0x77, 0x67, 0xfb, 0x8f, 0x3e, 0xb5, 0x4b, 0xed, 0x81, 0x8c, 0xe5, 0xe6, 0x28,
	0xf3, 0xd6, 0x86, 0x40, 0xb6, 0x38, 0xa3, 0x04, 0x02, 0xae, 0x82, 0xa6, 0x9f, 0x64, 0x9e, 0xd8,
	0x8f, 0x3c, 0x86, 0x19, 0x17, 0xce, 0x25, 0x55, 0xc3, 0xfe, 0xfc, 0xf1, 0x51, 0xbb, 0xb1, 0xbe,
	0xb3, 0x3b, 0x78, 0xf4, 0xe0, 0xa1, 0x92, 0x51, 0xc3, 0x4f, 0xb2, 0xc1, 0x7e, 0xa4, 0x07, 0xf0,
	0x33, 0x30, 0x1f, 0x61, 0x21, 0x3d, 0x92, 0xa6, 0x3c, 0xf5, 0x7c, 0x1e, 0x10, 0x07, 0xea, 0x9a,
	0x36, 0x95, 0xbc, 0xa9, 0xd4, 0x75, 0x1e, 0x10, 0xf8, 0x0c, 0xcc, 0x4d, 0xf8, 0xc5, 0x22, 0x74,
	0x16, 0x94, 0x5b, 0xff, 0xab, 0xa2, 0x75, 0xdd, 0x0b, 0x76, 0x97, 0x92, 0x00, 0xfb, 0xd2, 0x45,
	0xfa, 0x07, 0x0f, 0x23, 0x32, 0x90, 0x29, 0x65, 0x21, 0x9a, 0x1d, 0xa7, 0xff, 0x4e, 0x84, 0xb0,
	0x0f, 0x6a, 0xaa, 0x9d, 0x33, 0xe1, 0x5c, 0xee, 0x18, 0xdd, 0xb9, 0x95, 0xe5, 0x8b, 0x4a, 0x3e,
	0xd1, 0xec, 0xee, 0x40, 0x47, 0xa0, 0x22, 0x72, 0xe9, 0x16, 0xa8, 0xe5, 0x0a, 0x6c, 0x02, 0x6b,
	0x9d, 0xc7, 0x49, 0x44, 0x24, 0x09, 0xec, 0x12, 0x04, 0xa0, 0x76, 0x0f, 0xd3, 0x88, 0x04, 0xb6,
	0xb1, 0xf4, 0x8b, 0x05, 0x2c, 0xe5, 0x45, 0x62, 0xc2, 0xe4, 0xbf, 0x06, 0x53, 0xf8, 0xc3, 0x45,
	0xa4, 0x7b, 0x7a, 0x8e, 0x4a, 0x7f, 0x1e, 0xb5, 0x37, 0xff, 0x09, 0xf6, 0xd4, 0x85, 0xf8, 0x5b,
	0xbc, 0x7d, 0x01, 0x60, 0x84, 0x25, 0x61, 0xfe, 0xa1, 0x47, 0x99, 0x27, 0x88, 0xcf, 0x59, 0x20,
	0x34, 0xe3, 0x0c, 0x64, 0x17, 0x96, 0x2d, 0x36, 0xc8, 0x75, 0xb8, 0x00, 0xaa, 0xfb, 0x19, 0x49,
	0x0f, 0x35, 0xe0, 0x2c, 0x94, 0x0f, 0xe0, 0x37, 0xe3, 0x73, 0xa9, 0xea, 0x73, 0xe9, 0x5e, 0x74,
	0x2e, 0xe3, 0x9a, 0xbe, 0x73, 0x2a, 0xff, 0x11, 0xb6, 0x5d, 0x07, 0xd6, 0xf3, 0x2c, 0x8a, 0x3c,
	0xe1, 0x63, 0xa6, 0x01, 0x67, 0x22, 0x53, 0x09, 0x03, 0x1f, 0x33, 0xb8, 0x08, 0xcc, 0x00, 0x4b,
	0x3c, 0xc4, 0x82, 0x68, 0x30, 0x59, 0x68, 0x3c, 0x56, 0x81, 0x49, 0x84, 0x99, 0x17, 0x52, 0x91,
	0x33, 0xc9, 0x42, 0xa6, 0x12, 0xee, 0x53, 0x21, 0xcf, 0x22, 0xaf, 0xf9, 0x01, 0xe4, 0xcd, 0x9d,
	0x47, 0x9e, 0x03, 0xea, 0x0a, 0x66, 0x54, 0x93, 0x46, 0x59, 0x47, 0xc3, 0xf7, 0xb3, 0xce, 0x7e,
	0x3f, 0xeb, 0x16, 0x40, 0x95, 0xf1, 0x80, 0xa8, 0x76, 0x2f, 0x77, 0xcb, 0x28, 0x1f, 0xbc, 0xf3,
	0x52, 0x82, 0x1f, 0xff, 0x52, 0x5a, 0x05, 0x57, 0x28, 0x0b, 0xc8, 0x81, 0x97, 0x12, 0x9f, 0xc7,
	0x31, 0x61, 0x81, 0xf6, 0x54, 0x1d, 0x5a, 0xee, 0x5a, 0x68, 0x41, 0x1b, 0xd1, 0x59, 0x1b, 0xbc,
	0x0d, 0xea, 0x05, 0x46, 0x9d, 0x2b, 0xfa, 0xc2, 0x7c, 0x10, 0xbb, 0x23, 0xff, 0x09, 0xea, 0x5e,
	0xfd, 0x18, 0xea, 0x9e, 0x83, 0xde, 0xff, 0xa6, 0x80, 0xde, 0x0d, 0x00, 0x26, 0x78, 0xe7, 0xe8,
	0xba, 0x5a, 0x64, 0xcc, 0xba, 0x01, 0xb0, 0x4e, 0x31, 0x77, 0xed, 0x93, 0x30, 0x67, 0x92, 0x02,
	0x71, 0x53, 0xe1, 0x69, 0xbb, 0x62, 0x5a, 0x36, 0xd8, 0xae, 0x98, 0xc0, 0x6e, 0x6c, 0x57, 0xcc,
	0x05, 0xfb, 0xca, 0xd2, 0xcf, 0x33, 0xa0, 0xbe, 0x95, 0x6f, 0x1d, 0xae, 0x81, 0xba, 0xc8, 0x3f,
	0x03, 0x35, 0xb3, 0x1a, 0x17, 0x57, 0xb7, 0xf8, 0x5a, 0xec, 0x57, 0xd4, 0xb2, 0xd1, 0x28, 0x0a,
	0x6e, 0x82, 0x86, 0x3c, 0x05, 0xa8, 0x46, 0x52, 0x63, 0xe5, 0xd6, 0x14, 0xac, 0x45, 0x93, 0x71,
	0xf0, 0xae, 0xee, 0xe9, 0xbc, 0xdf, 0x85, 0x53, 0xeb, 0x94, 0xbb, 0x8d, 0x95, 0x9b, 0x1f, 0x24,
	0x03, 0x9a, 0x08, 0x82, 0x6b, 0xc0, 0x1a, 0x8f, 0x34, 0x93, 0xa6, 0xca, 0x70, 0x1a, 0xb3, 0x5d,
	0x31, 0x2b, 0x76, 0x75, 0xbb, 0x62, 0x56, 0xed, 0xda, 0xf2, 0x1d, 0x50, 0x2f, 0xae, 0x13, 0x34,
	0x41, 0xe5, 0x21, 0x67, 0xc4, 0x2e, 0xc1, 0x4b, 0xa0, 0x39, 0x88, 0xf8, 0xcb, 0xf1, 0x1b, 0xd2,
	0x36, 0xe0, 0x65, 0x30, 0x9f, 0x57, 0xfa, 0x54, 0x9c, 0x59, 0x1e, 0x82, 0xaa, 0xbe, 0x51, 0xd0,
	0x02, 0xd5, 0x5d, 0x26, 0x88, 0xb4, 0x4b, 0x10, 0x82, 0xb9, 0x9d, 0x08, 0x33, 0x44, 0xc2, 0x34,
	0xaf, 0x9c, 0x6d, 0x28, 0x6d, 0x90, 0x0d, 0x79, 0x22, 0x69, 0x8c, 0x23, 0x65, 0xb5, 0x67, 0x94,
	0xf6, 0x2d, 0x0d, 0xf7, 0xd6, 0xc7, 0x5d, 0x63, 0x97, 0x47, 0x1a, 0x1a, 0x7f, 0xb8, 0xd8, 0x95,
	0xfe, 0xb3, 0xd7, 0x7f, 0xb4, 0x4a, 0xaf, 0x8f, 0x5b, 0xc6, 0x9b, 0xe3, 0x96, 0xf1, 0xf6, 0xb8,
	0x65, 0xfc, 0x7e, 0xdc, 0x32, 0x5e, 0x9d, 0xb4, 0x4a, 0x6f, 0x4e, 0x5a, 0xa5, 0xb7, 0x27, 0xad,
	0xd2, 0xd3, 0xaf, 0xa7, 0x7e, 0x05, 0x9c, 0xfb, 0x6f, 0x32, 0xac, 0xe9, 0x76, 0x5e, 0xfd, 0x2b,
	0x00, 0x00, 0xff, 0xff, 0xe2, 0x92, 0xed, 0x6b, 0xbb, 0x0c, 0x00, 0x00,
}

func (m *Session) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Session) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Session) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ID.Size()
		i -= size
		if _, err := m.ID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintInsights(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Transaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Transaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Transaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LastErrorMsg) > 0 {
		i -= len(m.LastErrorMsg)
		copy(dAtA[i:], m.LastErrorMsg)
		i = encodeVarintInsights(dAtA, i, uint64(len(m.LastErrorMsg)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.Status != 0 {
		i = encodeVarintInsights(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if len(m.LastErrorCode) > 0 {
		i -= len(m.LastErrorCode)
		copy(dAtA[i:], m.LastErrorCode)
		i = encodeVarintInsights(dAtA, i, uint64(len(m.LastErrorCode)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.CPUSQLNanos != 0 {
		i = encodeVarintInsights(dAtA, i, uint64(m.CPUSQLNanos))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if len(m.StmtExecutionIDs) > 0 {
		for iNdEx := len(m.StmtExecutionIDs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.StmtExecutionIDs[iNdEx].Size()
				i -= size
				if _, err := m.StmtExecutionIDs[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintInsights(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	if len(m.Causes) > 0 {
		dAtA2 := make([]byte, len(m.Causes)*10)
		var j1 int
		for _, num := range m.Causes {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintInsights(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.Problems) > 0 {
		dAtA4 := make([]byte, len(m.Problems)*10)
		var j3 int
		for _, num := range m.Problems {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintInsights(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x72
	}
	if len(m.AutoRetryReason) > 0 {
		i -= len(m.AutoRetryReason)
		copy(dAtA[i:], m.AutoRetryReason)
		i = encodeVarintInsights(dAtA, i, uint64(len(m.AutoRetryReason)))
		i--
		dAtA[i] = 0x6a
	}
	if m.RetryCount != 0 {
		i = encodeVarintInsights(dAtA, i, uint64(m.RetryCount))
		i--
		dAtA[i] = 0x60
	}
	if m.RowsWritten != 0 {
		i = encodeVarintInsights(dAtA, i, uint64(m.RowsWritten))
		i--
		dAtA[i] = 0x58
	}
	if m.RowsRead != 0 {
		i = encodeVarintInsights(dAtA, i, uint64(m.RowsRead))
		i--
		dAtA[i] = 0x50
	}
	if len(m.ApplicationName) > 0 {
		i -= len(m.ApplicationName)
		copy(dAtA[i:], m.ApplicationName)
		i = encodeVarintInsights(dAtA, i, uint64(len(m.ApplicationName)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.User) > 0 {
		i -= len(m.User)
		copy(dAtA[i:], m.User)
		i = encodeVarintInsights(dAtA, i, uint64(len(m.User)))
		i--
		dAtA[i] = 0x42
	}
	n5, err5 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintInsights(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x3a
	n6, err6 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintInsights(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0x32
	if m.Contention != nil {
		n7, err7 := github_com_gogo_protobuf_types.StdDurationMarshalTo(*m.Contention, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(*m.Contention):])
		if err7 != nil {
			return 0, err7
		}
		i -= n7
		i = encodeVarintInsights(dAtA, i, uint64(n7))
		i--
		dAtA[i] = 0x2a
	}
	if m.ImplicitTxn {
		i--
		if m.ImplicitTxn {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.UserPriority) > 0 {
		i -= len(m.UserPriority)
		copy(dAtA[i:], m.UserPriority)
		i = encodeVarintInsights(dAtA, i, uint64(len(m.UserPriority)))
		i--
		dAtA[i] = 0x1a
	}
	if m.FingerprintID != 0 {
		i = encodeVarintInsights(dAtA, i, uint64(m.FingerprintID))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.ID.Size()
		i -= size
		if _, err := m.ID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintInsights(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Statement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Statement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Statement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ErrorMsg) > 0 {
		i -= len(m.ErrorMsg)
		copy(dAtA[i:], m.ErrorMsg)
		i = encodeVarintInsights(dAtA, i, uint64(len(m.ErrorMsg)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xca
	}
	if len(m.ErrorCode) > 0 {
		i -= len(m.ErrorCode)
		copy(dAtA[i:], m.ErrorCode)
		i = encodeVarintInsights(dAtA, i, uint64(len(m.ErrorCode)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc2
	}
	if m.CPUSQLNanos != 0 {
		i = encodeVarintInsights(dAtA, i, uint64(m.CPUSQLNanos))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb8
	}
	if len(m.Causes) > 0 {
		dAtA9 := make([]byte, len(m.Causes)*10)
		var j8 int
		for _, num := range m.Causes {
			for num >= 1<<7 {
				dAtA9[j8] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j8++
			}
			dAtA9[j8] = uint8(num)
			j8++
		}
		i -= j8
		copy(dAtA[i:], dAtA9[:j8])
		i = encodeVarintInsights(dAtA, i, uint64(j8))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb2
	}
	if m.Problem != 0 {
		i = encodeVarintInsights(dAtA, i, uint64(m.Problem))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if len(m.IndexRecommendations) > 0 {
		for iNdEx := len(m.IndexRecommendations) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.IndexRecommendations[iNdEx])
			copy(dAtA[i:], m.IndexRecommendations[iNdEx])
			i = encodeVarintInsights(dAtA, i, uint64(len(m.IndexRecommendations[iNdEx])))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x9a
		}
	}
	if m.Contention != nil {
		n10, err10 := github_com_gogo_protobuf_types.StdDurationMarshalTo(*m.Contention, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(*m.Contention):])
		if err10 != nil {
			return 0, err10
		}
		i -= n10
		i = encodeVarintInsights(dAtA, i, uint64(n10))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if len(m.Nodes) > 0 {
		dAtA12 := make([]byte, len(m.Nodes)*10)
		var j11 int
		for _, num1 := range m.Nodes {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA12[j11] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j11++
			}
			dAtA12[j11] = uint8(num)
			j11++
		}
		i -= j11
		copy(dAtA[i:], dAtA12[:j11])
		i = encodeVarintInsights(dAtA, i, uint64(j11))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.AutoRetryReason) > 0 {
		i -= len(m.AutoRetryReason)
		copy(dAtA[i:], m.AutoRetryReason)
		i = encodeVarintInsights(dAtA, i, uint64(len(m.AutoRetryReason)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.Retries != 0 {
		i = encodeVarintInsights(dAtA, i, uint64(m.Retries))
		i--
		dAtA[i] = 0x78
	}
	if m.RowsWritten != 0 {
		i = encodeVarintInsights(dAtA, i, uint64(m.RowsWritten))
		i--
		dAtA[i] = 0x70
	}
	if m.RowsRead != 0 {
		i = encodeVarintInsights(dAtA, i, uint64(m.RowsRead))
		i--
		dAtA[i] = 0x68
	}
	if len(m.PlanGist) > 0 {
		i -= len(m.PlanGist)
		copy(dAtA[i:], m.PlanGist)
		i = encodeVarintInsights(dAtA, i, uint64(len(m.PlanGist)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Database) > 0 {
		i -= len(m.Database)
		copy(dAtA[i:], m.Database)
		i = encodeVarintInsights(dAtA, i, uint64(len(m.Database)))
		i--
		dAtA[i] = 0x5a
	}
	if m.FullScan {
		i--
		if m.FullScan {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	n13, err13 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime):])
	if err13 != nil {
		return 0, err13
	}
	i -= n13
	i = encodeVarintInsights(dAtA, i, uint64(n13))
	i--
	dAtA[i] = 0x3a
	n14, err14 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err14 != nil {
		return 0, err14
	}
	i -= n14
	i = encodeVarintInsights(dAtA, i, uint64(n14))
	i--
	dAtA[i] = 0x32
	if m.Status != 0 {
		i = encodeVarintInsights(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Query) > 0 {
		i -= len(m.Query)
		copy(dAtA[i:], m.Query)
		i = encodeVarintInsights(dAtA, i, uint64(len(m.Query)))
		i--
		dAtA[i] = 0x22
	}
	if m.LatencyInSeconds != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.LatencyInSeconds))))
		i--
		dAtA[i] = 0x19
	}
	if m.FingerprintID != 0 {
		i = encodeVarintInsights(dAtA, i, uint64(m.FingerprintID))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.ID.Size()
		i -= size
		if _, err := m.ID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintInsights(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Insight) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Insight) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Insight) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Statements) > 0 {
		for iNdEx := len(m.Statements) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Statements[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintInsights(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.Statement != nil {
		{
			size, err := m.Statement.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintInsights(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Transaction != nil {
		{
			size, err := m.Transaction.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintInsights(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Session.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintInsights(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintInsights(dAtA []byte, offset int, v uint64) int {
	offset -= sovInsights(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Session) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovInsights(uint64(l))
	return n
}

func (m *Transaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovInsights(uint64(l))
	if m.FingerprintID != 0 {
		n += 1 + sovInsights(uint64(m.FingerprintID))
	}
	l = len(m.UserPriority)
	if l > 0 {
		n += 1 + l + sovInsights(uint64(l))
	}
	if m.ImplicitTxn {
		n += 2
	}
	if m.Contention != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdDuration(*m.Contention)
		n += 1 + l + sovInsights(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovInsights(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovInsights(uint64(l))
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovInsights(uint64(l))
	}
	l = len(m.ApplicationName)
	if l > 0 {
		n += 1 + l + sovInsights(uint64(l))
	}
	if m.RowsRead != 0 {
		n += 1 + sovInsights(uint64(m.RowsRead))
	}
	if m.RowsWritten != 0 {
		n += 1 + sovInsights(uint64(m.RowsWritten))
	}
	if m.RetryCount != 0 {
		n += 1 + sovInsights(uint64(m.RetryCount))
	}
	l = len(m.AutoRetryReason)
	if l > 0 {
		n += 1 + l + sovInsights(uint64(l))
	}
	if len(m.Problems) > 0 {
		l = 0
		for _, e := range m.Problems {
			l += sovInsights(uint64(e))
		}
		n += 1 + sovInsights(uint64(l)) + l
	}
	if len(m.Causes) > 0 {
		l = 0
		for _, e := range m.Causes {
			l += sovInsights(uint64(e))
		}
		n += 1 + sovInsights(uint64(l)) + l
	}
	if len(m.StmtExecutionIDs) > 0 {
		for _, e := range m.StmtExecutionIDs {
			l = e.Size()
			n += 2 + l + sovInsights(uint64(l))
		}
	}
	if m.CPUSQLNanos != 0 {
		n += 2 + sovInsights(uint64(m.CPUSQLNanos))
	}
	l = len(m.LastErrorCode)
	if l > 0 {
		n += 2 + l + sovInsights(uint64(l))
	}
	if m.Status != 0 {
		n += 2 + sovInsights(uint64(m.Status))
	}
	l = len(m.LastErrorMsg)
	if l > 0 {
		n += 2 + l + sovInsights(uint64(l))
	}
	return n
}

func (m *Statement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovInsights(uint64(l))
	if m.FingerprintID != 0 {
		n += 1 + sovInsights(uint64(m.FingerprintID))
	}
	if m.LatencyInSeconds != 0 {
		n += 9
	}
	l = len(m.Query)
	if l > 0 {
		n += 1 + l + sovInsights(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovInsights(uint64(m.Status))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovInsights(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovInsights(uint64(l))
	if m.FullScan {
		n += 2
	}
	l = len(m.Database)
	if l > 0 {
		n += 1 + l + sovInsights(uint64(l))
	}
	l = len(m.PlanGist)
	if l > 0 {
		n += 1 + l + sovInsights(uint64(l))
	}
	if m.RowsRead != 0 {
		n += 1 + sovInsights(uint64(m.RowsRead))
	}
	if m.RowsWritten != 0 {
		n += 1 + sovInsights(uint64(m.RowsWritten))
	}
	if m.Retries != 0 {
		n += 1 + sovInsights(uint64(m.Retries))
	}
	l = len(m.AutoRetryReason)
	if l > 0 {
		n += 2 + l + sovInsights(uint64(l))
	}
	if len(m.Nodes) > 0 {
		l = 0
		for _, e := range m.Nodes {
			l += sovInsights(uint64(e))
		}
		n += 2 + sovInsights(uint64(l)) + l
	}
	if m.Contention != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdDuration(*m.Contention)
		n += 2 + l + sovInsights(uint64(l))
	}
	if len(m.IndexRecommendations) > 0 {
		for _, s := range m.IndexRecommendations {
			l = len(s)
			n += 2 + l + sovInsights(uint64(l))
		}
	}
	if m.Problem != 0 {
		n += 2 + sovInsights(uint64(m.Problem))
	}
	if len(m.Causes) > 0 {
		l = 0
		for _, e := range m.Causes {
			l += sovInsights(uint64(e))
		}
		n += 2 + sovInsights(uint64(l)) + l
	}
	if m.CPUSQLNanos != 0 {
		n += 2 + sovInsights(uint64(m.CPUSQLNanos))
	}
	l = len(m.ErrorCode)
	if l > 0 {
		n += 2 + l + sovInsights(uint64(l))
	}
	l = len(m.ErrorMsg)
	if l > 0 {
		n += 2 + l + sovInsights(uint64(l))
	}
	return n
}

func (m *Insight) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Session.Size()
	n += 1 + l + sovInsights(uint64(l))
	if m.Transaction != nil {
		l = m.Transaction.Size()
		n += 1 + l + sovInsights(uint64(l))
	}
	if m.Statement != nil {
		l = m.Statement.Size()
		n += 1 + l + sovInsights(uint64(l))
	}
	if len(m.Statements) > 0 {
		for _, e := range m.Statements {
			l = e.Size()
			n += 1 + l + sovInsights(uint64(l))
		}
	}
	return n
}

func sovInsights(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozInsights(x uint64) (n int) {
	return sovInsights(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Session) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInsights
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Session: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Session: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInsights(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInsights
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Transaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInsights
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Transaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Transaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FingerprintID", wireType)
			}
			m.FingerprintID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FingerprintID |= github_com_cockroachdb_cockroach_pkg_sql_appstatspb.TransactionFingerprintID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserPriority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserPriority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImplicitTxn", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ImplicitTxn = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contention", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Contention == nil {
				m.Contention = new(time.Duration)
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(m.Contention, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApplicationName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowsRead", wireType)
			}
			m.RowsRead = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RowsRead |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowsWritten", wireType)
			}
			m.RowsWritten = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RowsWritten |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetryCount", wireType)
			}
			m.RetryCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetryCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoRetryReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AutoRetryReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType == 0 {
				var v Problem
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowInsights
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= Problem(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Problems = append(m.Problems, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowInsights
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthInsights
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthInsights
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.Problems) == 0 {
					m.Problems = make([]Problem, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v Problem
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowInsights
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= Problem(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Problems = append(m.Problems, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Problems", wireType)
			}
		case 15:
			if wireType == 0 {
				var v Cause
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowInsights
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= Cause(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Causes = append(m.Causes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowInsights
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthInsights
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthInsights
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.Causes) == 0 {
					m.Causes = make([]Cause, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v Cause
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowInsights
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= Cause(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Causes = append(m.Causes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Causes", wireType)
			}
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StmtExecutionIDs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cockroachdb_cockroach_pkg_sql_clusterunique.ID
			m.StmtExecutionIDs = append(m.StmtExecutionIDs, v)
			if err := m.StmtExecutionIDs[len(m.StmtExecutionIDs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CPUSQLNanos", wireType)
			}
			m.CPUSQLNanos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CPUSQLNanos |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastErrorCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastErrorCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Transaction_Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastErrorMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastErrorMsg = github_com_cockroachdb_redact.RedactableString(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInsights(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInsights
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Statement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInsights
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Statement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Statement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FingerprintID", wireType)
			}
			m.FingerprintID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FingerprintID |= github_com_cockroachdb_cockroach_pkg_sql_appstatspb.StmtFingerprintID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatencyInSeconds", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.LatencyInSeconds = float64(math.Float64frombits(v))
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Query", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Query = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Statement_Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FullScan", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FullScan = bool(v != 0)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Database", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Database = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlanGist", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlanGist = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowsRead", wireType)
			}
			m.RowsRead = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RowsRead |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowsWritten", wireType)
			}
			m.RowsWritten = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RowsWritten |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Retries", wireType)
			}
			m.Retries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Retries |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoRetryReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AutoRetryReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowInsights
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Nodes = append(m.Nodes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowInsights
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthInsights
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthInsights
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Nodes) == 0 {
					m.Nodes = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowInsights
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Nodes = append(m.Nodes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contention", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Contention == nil {
				m.Contention = new(time.Duration)
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(m.Contention, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexRecommendations", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IndexRecommendations = append(m.IndexRecommendations, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Problem", wireType)
			}
			m.Problem = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Problem |= Problem(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 22:
			if wireType == 0 {
				var v Cause
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowInsights
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= Cause(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Causes = append(m.Causes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowInsights
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthInsights
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthInsights
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.Causes) == 0 {
					m.Causes = make([]Cause, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v Cause
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowInsights
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= Cause(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Causes = append(m.Causes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Causes", wireType)
			}
		case 23:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CPUSQLNanos", wireType)
			}
			m.CPUSQLNanos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CPUSQLNanos |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 24:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorMsg = github_com_cockroachdb_redact.RedactableString(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInsights(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInsights
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Insight) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInsights
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Insight: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Insight: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Session", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Session.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transaction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Transaction == nil {
				m.Transaction = &Transaction{}
			}
			if err := m.Transaction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Statement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Statement == nil {
				m.Statement = &Statement{}
			}
			if err := m.Statement.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Statements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInsights
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInsights
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Statements = append(m.Statements, &Statement{})
			if err := m.Statements[len(m.Statements)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInsights(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInsights
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipInsights(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowInsights
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInsights
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthInsights
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupInsights
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthInsights
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthInsights        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowInsights          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupInsights = fmt.Errorf("proto: unexpected end of group")
)

