// Code generated by goyacc -p plpgsql -o bazel-out/darwin_arm64-fastbuild/bin/pkg/sql/plpgsql/parser/plpgsql.go plpgsql-gen.y. DO NOT EDIT.

//line plpgsql-gen.y:2
package parser

import __yyfmt__ "fmt"

//line plpgsql-gen.y:2

import (
	"strings"

	"github.com/cockroachdb/cockroach/pkg/build"
	"github.com/cockroachdb/cockroach/pkg/sql/parser"
	"github.com/cockroachdb/cockroach/pkg/sql/scanner"
	"github.com/cockroachdb/cockroach/pkg/sql/sem/plpgsqltree"
	"github.com/cockroachdb/cockroach/pkg/sql/sem/tree"
	"github.com/cockroachdb/cockroach/pkg/sql/types"
	"github.com/cockroachdb/errors"
	"github.com/cockroachdb/redact"
)

//line plpgsql-gen.y:19
func setErr(plpgsqllex plpgsqlLexer, err error) int {
	plpgsqllex.(*lexer).setErr(err)
	return 1
}

func unimplemented(plpgsqllex plpgsqlLexer, feature string) int {
	plpgsqllex.(*lexer).Unimplemented(feature)
	return 1
}

var _ scanner.ScanSymType = &plpgsqlSymType{}

func (s *plpgsqlSymType) ID() int32 {
	return s.id
}

func (s *plpgsqlSymType) SetID(id int32) {
	s.id = id
}

func (s *plpgsqlSymType) Pos() int32 {
	return s.pos
}

func (s *plpgsqlSymType) SetPos(pos int32) {
	s.pos = pos
}

func (s *plpgsqlSymType) Str() string {
	return s.str
}

func (s *plpgsqlSymType) SetStr(str string) {
	s.str = str
}

func (s *plpgsqlSymType) UnionVal() interface{} {
	return s.union.val
}

func (s *plpgsqlSymType) SetUnionVal(val interface{}) {
	s.union.val = val
}

func (s *plpgsqlSymType) plpgsqlScanSymType() {}

type plpgsqlSymUnion struct {
	val interface{}
}

func (u *plpgsqlSymUnion) block() *plpgsqltree.Block {
	return u.val.(*plpgsqltree.Block)
}

func (u *plpgsqlSymUnion) caseWhen() *plpgsqltree.CaseWhen {
	return u.val.(*plpgsqltree.CaseWhen)
}

func (u *plpgsqlSymUnion) caseWhens() []*plpgsqltree.CaseWhen {
	return u.val.([]*plpgsqltree.CaseWhen)
}

func (u *plpgsqlSymUnion) statement() plpgsqltree.Statement {
	return u.val.(plpgsqltree.Statement)
}

func (u *plpgsqlSymUnion) statements() []plpgsqltree.Statement {
	return u.val.([]plpgsqltree.Statement)
}

func (u *plpgsqlSymUnion) int32() int32 {
	return u.val.(int32)
}

func (u *plpgsqlSymUnion) uint32() uint32 {
	return u.val.(uint32)
}

func (u *plpgsqlSymUnion) bool() bool {
	return u.val.(bool)
}

func (u *plpgsqlSymUnion) numVal() *tree.NumVal {
	return u.val.(*tree.NumVal)
}

func (u *plpgsqlSymUnion) typ() tree.ResolvableTypeReference {
	return u.val.(tree.ResolvableTypeReference)
}

func (u *plpgsqlSymUnion) getDiagnosticsKind() plpgsqltree.GetDiagnosticsKind {
	return u.val.(plpgsqltree.GetDiagnosticsKind)
}

func (u *plpgsqlSymUnion) getDiagnosticsItem() *plpgsqltree.GetDiagnosticsItem {
	return u.val.(*plpgsqltree.GetDiagnosticsItem)
}

func (u *plpgsqlSymUnion) getDiagnosticsItemList() plpgsqltree.GetDiagnosticsItemList {
	return u.val.(plpgsqltree.GetDiagnosticsItemList)
}

func (u *plpgsqlSymUnion) elseIf() []plpgsqltree.ElseIf {
	return u.val.([]plpgsqltree.ElseIf)
}

func (u *plpgsqlSymUnion) open() *plpgsqltree.Open {
	return u.val.(*plpgsqltree.Open)
}

func (u *plpgsqlSymUnion) expr() plpgsqltree.Expr {
	if u.val == nil {
		return nil
	}
	return u.val.(plpgsqltree.Expr)
}

func (u *plpgsqlSymUnion) exprs() []plpgsqltree.Expr {
	return u.val.([]plpgsqltree.Expr)
}

func (u *plpgsqlSymUnion) raiseOption() *plpgsqltree.RaiseOption {
	return u.val.(*plpgsqltree.RaiseOption)
}

func (u *plpgsqlSymUnion) raiseOptions() []plpgsqltree.RaiseOption {
	return u.val.([]plpgsqltree.RaiseOption)
}

func (u *plpgsqlSymUnion) exception() *plpgsqltree.Exception {
	return u.val.(*plpgsqltree.Exception)
}

func (u *plpgsqlSymUnion) exceptions() []plpgsqltree.Exception {
	return u.val.([]plpgsqltree.Exception)
}

func (u *plpgsqlSymUnion) condition() *plpgsqltree.Condition {
	return u.val.(*plpgsqltree.Condition)
}

func (u *plpgsqlSymUnion) conditions() []plpgsqltree.Condition {
	return u.val.([]plpgsqltree.Condition)
}

func (u *plpgsqlSymUnion) cursorScrollOption() tree.CursorScrollOption {
	return u.val.(tree.CursorScrollOption)
}

func (u *plpgsqlSymUnion) sqlStatement() tree.Statement {
	return u.val.(tree.Statement)
}

//line plpgsql-gen.y:311
type plpgsqlSymType struct {
	yys   int
	id    int32
	pos   int32
	str   string
	union plpgsqlSymUnion
}

const IDENT = 57346
const UIDENT = 57347
const FCONST = 57348
const SCONST = 57349
const USCONST = 57350
const BCONST = 57351
const XCONST = 57352
const Op = 57353
const ICONST = 57354
const PARAM = 57355
const TYPECAST = 57356
const DOT_DOT = 57357
const COLON_EQUALS = 57358
const EQUALS_GREATER = 57359
const LESS_EQUALS = 57360
const GREATER_EQUALS = 57361
const NOT_EQUALS = 57362
const LESS_LESS = 57363
const GREATER_GREATER = 57364
const ABSOLUTE = 57365
const ALIAS = 57366
const ALL = 57367
const AND = 57368
const ARRAY = 57369
const ASSERT = 57370
const BACKWARD = 57371
const BEGIN = 57372
const BY = 57373
const CALL = 57374
const CASE = 57375
const CHAIN = 57376
const CLOSE = 57377
const COLLATE = 57378
const COLUMN = 57379
const COLUMN_NAME = 57380
const COMMIT = 57381
const CONSTANT = 57382
const CONSTRAINT = 57383
const CONSTRAINT_NAME = 57384
const CONTINUE = 57385
const CURRENT = 57386
const CURSOR = 57387
const DATATYPE = 57388
const DEBUG = 57389
const DECLARE = 57390
const DEFAULT = 57391
const DETAIL = 57392
const DIAGNOSTICS = 57393
const DO = 57394
const DUMP = 57395
const ELSE = 57396
const ELSIF = 57397
const END = 57398
const END_CASE = 57399
const END_IF = 57400
const ERRCODE = 57401
const ERROR = 57402
const EXCEPTION = 57403
const EXECUTE = 57404
const EXIT = 57405
const FETCH = 57406
const FIRST = 57407
const FOR = 57408
const FOREACH = 57409
const FORWARD = 57410
const FROM = 57411
const GET = 57412
const HINT = 57413
const IF = 57414
const IMPORT = 57415
const IN = 57416
const INFO = 57417
const INSERT = 57418
const INTO = 57419
const IS = 57420
const LAST = 57421
const LOG = 57422
const LOOP = 57423
const MERGE = 57424
const MESSAGE = 57425
const MESSAGE_TEXT = 57426
const MOVE = 57427
const NEXT = 57428
const NO = 57429
const NO_SCROLL = 57430
const NOT = 57431
const NOTICE = 57432
const NULL = 57433
const OPEN = 57434
const OPTION = 57435
const OR = 57436
const PERFORM = 57437
const PG_CONTEXT = 57438
const PG_DATATYPE_NAME = 57439
const PG_EXCEPTION_CONTEXT = 57440
const PG_EXCEPTION_DETAIL = 57441
const PG_EXCEPTION_HINT = 57442
const PRINT_STRICT_PARAMS = 57443
const PRIOR = 57444
const QUERY = 57445
const RAISE = 57446
const RELATIVE = 57447
const RETURN = 57448
const RETURN_NEXT = 57449
const RETURN_QUERY = 57450
const RETURNED_SQLSTATE = 57451
const REVERSE = 57452
const ROLLBACK = 57453
const ROW_COUNT = 57454
const ROWTYPE = 57455
const SCHEMA = 57456
const SCHEMA_NAME = 57457
const SCROLL = 57458
const SLICE = 57459
const SQLSTATE = 57460
const STACKED = 57461
const STRICT = 57462
const TABLE = 57463
const TABLE_NAME = 57464
const THEN = 57465
const TO = 57466
const TYPE = 57467
const UPSERT = 57468
const USE_COLUMN = 57469
const USE_VARIABLE = 57470
const USING = 57471
const VARIABLE_CONFLICT = 57472
const WARNING = 57473
const WHEN = 57474
const WHILE = 57475

var plpgsqlToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"UIDENT",
	"FCONST",
	"SCONST",
	"USCONST",
	"BCONST",
	"XCONST",
	"Op",
	"ICONST",
	"PARAM",
	"TYPECAST",
	"DOT_DOT",
	"COLON_EQUALS",
	"EQUALS_GREATER",
	"LESS_EQUALS",
	"GREATER_EQUALS",
	"NOT_EQUALS",
	"LESS_LESS",
	"GREATER_GREATER",
	"ABSOLUTE",
	"ALIAS",
	"ALL",
	"AND",
	"ARRAY",
	"ASSERT",
	"BACKWARD",
	"BEGIN",
	"BY",
	"CALL",
	"CASE",
	"CHAIN",
	"CLOSE",
	"COLLATE",
	"COLUMN",
	"COLUMN_NAME",
	"COMMIT",
	"CONSTANT",
	"CONSTRAINT",
	"CONSTRAINT_NAME",
	"CONTINUE",
	"CURRENT",
	"CURSOR",
	"DATATYPE",
	"DEBUG",
	"DECLARE",
	"DEFAULT",
	"DETAIL",
	"DIAGNOSTICS",
	"DO",
	"DUMP",
	"ELSE",
	"ELSIF",
	"END",
	"END_CASE",
	"END_IF",
	"ERRCODE",
	"ERROR",
	"EXCEPTION",
	"EXECUTE",
	"EXIT",
	"FETCH",
	"FIRST",
	"FOR",
	"FOREACH",
	"FORWARD",
	"FROM",
	"GET",
	"HINT",
	"IF",
	"IMPORT",
	"IN",
	"INFO",
	"INSERT",
	"INTO",
	"IS",
	"LAST",
	"LOG",
	"LOOP",
	"MERGE",
	"MESSAGE",
	"MESSAGE_TEXT",
	"MOVE",
	"NEXT",
	"NO",
	"NO_SCROLL",
	"NOT",
	"NOTICE",
	"NULL",
	"OPEN",
	"OPTION",
	"OR",
	"PERFORM",
	"PG_CONTEXT",
	"PG_DATATYPE_NAME",
	"PG_EXCEPTION_CONTEXT",
	"PG_EXCEPTION_DETAIL",
	"PG_EXCEPTION_HINT",
	"PRINT_STRICT_PARAMS",
	"PRIOR",
	"QUERY",
	"RAISE",
	"RELATIVE",
	"RETURN",
	"RETURN_NEXT",
	"RETURN_QUERY",
	"RETURNED_SQLSTATE",
	"REVERSE",
	"ROLLBACK",
	"ROW_COUNT",
	"ROWTYPE",
	"SCHEMA",
	"SCHEMA_NAME",
	"SCROLL",
	"SLICE",
	"SQLSTATE",
	"STACKED",
	"STRICT",
	"TABLE",
	"TABLE_NAME",
	"THEN",
	"TO",
	"TYPE",
	"UPSERT",
	"USE_COLUMN",
	"USE_VARIABLE",
	"USING",
	"VARIABLE_CONFLICT",
	"WARNING",
	"WHEN",
	"WHILE",
	"';'",
	"'('",
	"','",
	"'='",
}

var plpgsqlStatenames = [...]string{}

const plpgsqlEofCode = 1
const plpgsqlErrCode = 2
const plpgsqlInitialStackSize = 16

//line plpgsql-gen.y:1690

//line yacctab:1
var plpgsqlExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 103,
	45, 16,
	-2, 31,
	-1, 107,
	30, 180,
	48, 180,
	56, 166,
	-2, 182,
	-1, 238,
	30, 180,
	48, 180,
	-2, 182,
	-1, 265,
	30, 181,
	48, 181,
	-2, 183,
	-1, 278,
	30, 180,
	48, 180,
	54, 87,
	55, 87,
	58, 87,
	-2, 182,
	-1, 323,
	30, 180,
	48, 180,
	56, 170,
	132, 170,
	-2, 182,
	-1, 327,
	30, 180,
	48, 180,
	57, 97,
	-2, 182,
	-1, 354,
	30, 180,
	48, 180,
	54, 95,
	57, 95,
	132, 95,
	-2, 182,
	-1, 366,
	30, 180,
	48, 180,
	58, 90,
	-2, 182,
	-1, 374,
	30, 180,
	48, 180,
	54, 88,
	55, 88,
	58, 88,
	-2, 182,
}

const plpgsqlPrivate = 57344

const plpgsqlLast = 1157

var plpgsqlAct = [...]int16{
	238, 237, 239, 185, 11, 299, 311, 191, 295, 182,
	298, 206, 293, 105, 192, 229, 207, 235, 111, 9,
	244, 241, 179, 215, 144, 341, 343, 184, 344, 184,
	294, 340, 199, 341, 189, 190, 246, 225, 245, 113,
	373, 168, 368, 367, 363, 358, 204, 357, 154, 187,
	349, 348, 158, 146, 337, 164, 334, 329, 277, 166,
	201, 270, 319, 149, 264, 200, 261, 114, 260, 256,
	255, 254, 159, 253, 248, 202, 284, 214, 181, 6,
	281, 236, 156, 148, 162, 258, 250, 180, 296, 249,
	160, 275, 145, 169, 371, 328, 170, 233, 107, 289,
	176, 188, 172, 196, 105, 163, 144, 210, 320, 262,
	267, 165, 161, 195, 330, 157, 203, 100, 285, 197,
	274, 273, 332, 168, 153, 287, 150, 151, 152, 370,
	154, 167, 313, 272, 158, 146, 174, 164, 346, 364,
	326, 166, 352, 351, 8, 149, 171, 316, 183, 177,
	183, 110, 257, 175, 159, 220, 314, 193, 236, 353,
	97, 356, 263, 117, 156, 148, 162, 112, 216, 265,
	106, 4, 160, 333, 145, 169, 208, 297, 170, 223,
	276, 312, 211, 218, 172, 226, 213, 163, 212, 118,
	2, 217, 155, 165, 161, 230, 205, 157, 271, 232,
	251, 227, 224, 221, 242, 242, 153, 5, 150, 151,
	152, 252, 243, 167, 247, 113, 1, 108, 292, 291,
	361, 310, 209, 279, 234, 269, 228, 178, 171, 115,
	99, 259, 98, 7, 278, 305, 101, 125, 121, 306,
	282, 143, 286, 114, 307, 283, 142, 141, 302, 140,
	139, 138, 280, 137, 136, 135, 134, 304, 133, 124,
	132, 131, 130, 290, 129, 128, 127, 126, 123, 303,
	122, 120, 119, 116, 350, 323, 318, 325, 300, 198,
	147, 301, 327, 322, 3, 240, 288, 331, 186, 194,
	230, 324, 219, 173, 321, 315, 266, 109, 317, 103,
	335, 0, 0, 0, 0, 336, 339, 338, 0, 0,
	342, 0, 309, 0, 0, 0, 0, 0, 0, 308,
	0, 0, 345, 0, 0, 347, 0, 0, 0, 354,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 355,
	0, 0, 0, 0, 0, 104, 0, 359, 0, 0,
	362, 360, 0, 366, 0, 365, 0, 0, 0, 369,
	0, 0, 0, 0, 12, 13, 0, 14, 15, 16,
	17, 372, 374, 18, 0, 19, 20, 21, 22, 23,
	24, 25, 26, 27, 28, 29, 30, 31, 32, 102,
	33, 34, 35, 36, 37, 0, 38, 0, 0, 0,
	39, 40, 41, 0, 42, 43, 44, 0, 0, 45,
	0, 46, 47, 0, 48, 0, 49, 50, 0, 51,
	52, 53, 0, 54, 55, 56, 57, 58, 59, 60,
	0, 61, 0, 62, 63, 0, 64, 65, 66, 67,
	68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
	78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
	88, 10, 89, 90, 0, 0, 91, 92, 93, 94,
	0, 95, 96, 0, 0, 0, 0, 0, 0, 0,
	12, 13, 0, 14, 15, 16, 17, 0, 0, 18,
	0, 19, 20, 21, 22, 23, 24, 25, 26, 27,
	28, 29, 30, 31, 32, 0, 33, 34, 35, 36,
	37, 0, 38, 0, 0, 0, 39, 40, 41, 0,
	42, 43, 44, 0, 0, 45, 0, 46, 47, 0,
	48, 0, 49, 50, 0, 51, 52, 53, 0, 54,
	55, 56, 57, 58, 59, 60, 0, 61, 0, 62,
	63, 0, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 10, 89, 90,
	0, 0, 91, 92, 93, 94, 0, 95, 96, 0,
	0, 0, 0, 0, 0, 0, 12, 13, 0, 14,
	15, 16, 17, 0, 0, 18, 0, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 0, 33, 34, 35, 36, 37, 0, 38, 0,
	0, 0, 39, 40, 41, 0, 42, 43, 44, 0,
	0, 45, 0, 46, 47, 0, 48, 0, 49, 50,
	0, 51, 52, 53, 0, 54, 55, 56, 57, 58,
	59, 60, 0, 61, 0, 62, 63, 0, 64, 65,
	66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
	76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
	86, 231, 88, 268, 89, 90, 0, 0, 91, 92,
	93, 94, 0, 95, 96, 0, 0, 0, 0, 0,
	0, 0, 12, 13, 0, 14, 15, 16, 17, 0,
	0, 18, 0, 19, 20, 21, 22, 23, 24, 25,
	26, 27, 28, 29, 30, 31, 32, 0, 33, 34,
	35, 36, 37, 0, 38, 0, 0, 0, 39, 40,
	41, 0, 42, 43, 44, 0, 0, 45, 0, 46,
	47, 0, 48, 0, 49, 50, 0, 51, 52, 53,
	0, 54, 55, 56, 57, 58, 59, 60, 0, 61,
	0, 62, 63, 0, 64, 65, 66, 67, 68, 69,
	70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
	80, 81, 82, 83, 84, 85, 86, 87, 88, 222,
	89, 90, 0, 0, 91, 92, 93, 94, 0, 95,
	96, 0, 0, 0, 0, 0, 0, 0, 12, 13,
	0, 14, 15, 16, 17, 0, 0, 18, 0, 19,
	20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
	30, 31, 32, 0, 33, 34, 35, 36, 37, 0,
	38, 0, 0, 0, 39, 40, 41, 0, 42, 43,
	44, 0, 0, 45, 0, 46, 47, 0, 48, 0,
	49, 50, 0, 51, 52, 53, 0, 54, 55, 56,
	57, 58, 59, 60, 0, 61, 0, 62, 63, 0,
	64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
	74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
	84, 85, 86, 87, 88, 0, 89, 90, 0, 0,
	91, 92, 93, 94, 0, 95, 96, 12, 13, 0,
	14, 15, 16, 17, 0, 0, 18, 0, 19, 20,
	21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
	31, 32, 0, 33, 34, 35, 36, 37, 0, 38,
	0, 0, 0, 39, 40, 41, 0, 42, 43, 44,
	0, 0, 45, 0, 46, 47, 0, 48, 0, 49,
	50, 0, 51, 52, 53, 0, 54, 55, 56, 57,
	58, 59, 60, 0, 61, 0, 62, 63, 0, 64,
	65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
	75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
	85, 86, 87, 88, 144, 89, 90, 0, 0, 91,
	92, 93, 94, 0, 95, 96, 0, 0, 0, 0,
	0, 168, 0, 0, 0, 0, 0, 0, 154, 0,
	0, 0, 158, 146, 0, 164, 0, 0, 0, 166,
	0, 0, 0, 149, 0, 0, 0, 0, 0, 0,
	0, 0, 159, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 156, 148, 162, 0, 0, 0, 0, 0,
	160, 0, 145, 169, 0, 0, 170, 0, 0, 0,
	0, 0, 172, 0, 0, 163, 0, 0, 0, 0,
	0, 165, 161, 0, 0, 157, 0, 0, 0, 0,
	0, 0, 0, 0, 153, 0, 150, 151, 152, 0,
	0, 167, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 171,
}

var plpgsqlPact = [...]int16{
	150, -1000, -55, 96, 457, -1000, -1000, 130, 341, 148,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 341,
	-1000, -1000, -1000, 127, -1000, -1000, -1000, 102, -1000, -1000,
	70, 108, -1000, -16, -1000, 93, -1000, -45, -56, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 11, -1000, -1000, -32, 457, 457,
	-1000, 27, 0, -15, -1000, -1000, -1000, -1000, -1000, -1000,
	63, 184, -1000, -1000, 182, -57, 142, 142, 457, -1000,
	-1000, -1000, -1000, 119, 805, -98, -1000, 457, -45, -1000,
	573, -1000, -1000, -1000, -1000, -26, -51, -1000, -1000, 457,
	457, -96, -1000, -96, -60, -1000, -1000, -1000, 82, -1000,
	-1000, -1000, -1000, -1000, -1000, -61, -63, -64, -65, 101,
	-1000, -1000, -49, -66, -1000, -68, 75, -70, 147, 21,
	689, -73, -1000, -1000, 55, -1000, -1000, -1000, -3, -1000,
	-1000, 173, -76, -1000, 26, -1000, -1000, 457, 20, 37,
	-1000, 51, -1000, -18, -1000, -1000, -1000, -1000, -1000, -106,
	-41, 170, 198, -1000, -1000, -1000, -1000, 177, -1000, 66,
	-1000, -1000, -1000, 122, -1000, -1000, 13, 17, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 573, -1000, -1000, 1030, 83,
	-1000, -1000, -28, -77, 33, -1000, -1000, -1000, 48, 161,
	-78, -41, -106, -1000, -1000, -80, 198, -41, -103, -1000,
	11, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-108, -1000, 11, 76, -1000, -1000, -1000, -83, -1000, -1000,
	-1000, -1000, -84, 1030, -1000, 88, 126, 1030, -1000, -1000,
	-1000, 457, 134, -1000, -1000, -87, -1000, -1000, -111, -89,
	-1000, 198, -1000, -1000, 177, 914, -1000, -90, -1000, -1000,
	81, -1000, -1000, -91, 1030, -92, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 57, -29, 1030, -1000, -1000, -1000,
	-94, -1000, -1000, -1000, 1030,
}

var plpgsqlPgo = [...]int16{
	0, 299, 298, 297, 296, 295, 294, 293, 292, 16,
	292, 11, 289, 3, 2, 288, 20, 21, 286, 285,
	14, 284, 280, 7, 280, 279, 278, 0, 277, 274,
	1, 189, 273, 272, 271, 270, 268, 267, 266, 265,
	264, 262, 261, 260, 259, 258, 256, 255, 254, 253,
	251, 250, 249, 247, 246, 241, 238, 237, 117, 236,
	233, 232, 230, 229, 227, 22, 226, 15, 17, 224,
	223, 222, 221, 6, 220, 5, 10, 8, 12, 219,
	218, 18, 23, 4, 216, 207, 203, 202, 198, 198,
	198, 9, 198, 196, 192, 192,
}

var plpgsqlR1 = [...]int8{
	0, 84, 85, 85, 31, 60, 60, 61, 61, 62,
	62, 58, 58, 59, 59, 59, 81, 81, 81, 6,
	87, 87, 89, 89, 90, 88, 88, 86, 86, 1,
	1, 3, 3, 7, 8, 8, 8, 4, 4, 5,
	5, 2, 2, 91, 91, 27, 27, 32, 32, 32,
	32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	32, 32, 32, 45, 46, 47, 33, 48, 71, 71,
	71, 72, 72, 73, 74, 92, 34, 28, 28, 29,
	29, 56, 15, 69, 69, 68, 70, 70, 35, 36,
	44, 19, 17, 57, 18, 18, 37, 38, 39, 39,
	39, 12, 24, 40, 40, 40, 40, 40, 25, 25,
	25, 25, 25, 25, 25, 77, 77, 76, 76, 75,
	26, 26, 26, 26, 26, 26, 26, 26, 26, 79,
	79, 80, 80, 78, 41, 93, 30, 42, 94, 94,
	94, 94, 94, 43, 49, 49, 49, 50, 51, 52,
	53, 54, 55, 82, 82, 82, 63, 63, 64, 64,
	65, 66, 66, 67, 67, 9, 11, 13, 14, 10,
	21, 21, 22, 22, 23, 23, 16, 16, 20, 20,
	83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
	83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
	83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
	83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
	83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
	83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
	83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
	83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
	83, 83, 83, 83, 83, 95, 95, 95, 95, 95,
	95, 95, 95, 95, 95, 95, 95, 95, 95, 95,
	95, 95, 95, 95, 95, 95, 95, 95, 95, 95,
	95,
}

var plpgsqlR2 = [...]int8{
	0, 2, 0, 1, 7, 2, 0, 1, 0, 2,
	1, 1, 1, 6, 5, 6, 0, 2, 1, 2,
	1, 0, 1, 3, 2, 1, 1, 1, 1, 1,
	1, 0, 1, 0, 0, 2, 2, 0, 2, 1,
	2, 1, 1, 1, 1, 0, 2, 2, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 3, 3, 4, 5, 0, 1,
	1, 3, 1, 3, 1, 1, 9, 0, 5, 0,
	2, 7, 0, 2, 1, 4, 0, 2, 5, 7,
	4, 2, 1, 8, 0, 2, 3, 3, 3, 2,
	2, 0, 0, 2, 6, 5, 6, 5, 1, 1,
	1, 1, 1, 1, 0, 2, 0, 3, 1, 2,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	0, 1, 2, 1, 3, 0, 3, 1, 1, 1,
	1, 1, 1, 1, 3, 5, 6, 1, 1, 3,
	2, 3, 3, 2, 3, 0, 0, 2, 2, 1,
	4, 3, 1, 1, 2, 0, 0, 0, 0, 0,
	0, 3, 0, 3, 0, 1, 1, 3, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1,
}

var plpgsqlChk = [...]int16{
	-1000, -84, -31, -21, 21, -85, 134, -60, 48, -20,
	4, -83, 23, 24, 26, 27, 28, 29, 32, 34,
	35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
	45, 46, 47, 49, 50, 51, 52, 53, 55, 59,
	60, 61, 63, 64, 65, 68, 70, 71, 73, 75,
	76, 78, 79, 80, 82, 83, 84, 85, 86, 87,
	88, 90, 92, 93, 95, 96, 97, 98, 99, 100,
	101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
	111, 112, 113, 114, 115, 116, 117, 118, 119, 121,
	122, 125, 126, 127, 128, 130, 131, 30, -61, -62,
	-58, -59, 48, -1, 4, -83, 22, -27, -58, -3,
	24, -81, 40, 88, 116, -63, -32, 61, -31, -33,
	-34, -56, -35, -36, -44, -57, -37, -38, -39, -40,
	-41, -42, -43, -45, -46, -47, -48, -49, -50, -51,
	-52, -53, -54, -55, 4, 72, 33, -22, 63, 43,
	106, 107, 108, 104, 28, -94, 62, 95, 32, 52,
	70, 92, 64, 85, 35, 91, 39, 111, 21, 73,
	76, 126, 82, -7, 66, 45, 116, 56, -64, -65,
	132, 134, -91, 137, 16, -13, -15, 81, 133, 66,
	67, -23, -20, -23, -12, 86, 103, 134, -25, 47,
	80, 75, 90, 131, 61, -93, -11, -9, -9, -71,
	44, 119, 4, 4, 134, -82, 26, -82, -20, -8,
	36, -86, 4, -83, -87, 135, -23, -65, -66, -67,
	-20, 118, -9, 123, -69, -68, 132, -30, -27, -14,
	-19, -17, -20, -17, -16, 134, 132, -16, 134, 7,
	4, 118, 129, 134, 134, 134, 134, 51, 134, -81,
	134, 134, 34, 87, 134, 22, -4, 89, 4, -83,
	134, -88, 78, 66, 123, 94, 7, 134, -27, -70,
	-68, 54, -13, -23, 56, 81, -30, 74, -18, 117,
	-9, -79, -80, -78, 136, -77, 129, 7, -76, -75,
	-26, 83, 50, 71, 59, 37, 41, 46, 121, 114,
	-72, -73, 4, 66, 34, -5, 134, -2, -91, 49,
	91, -6, -11, -27, -67, -28, 57, -27, 123, 134,
	81, -30, 74, 12, 134, -77, -78, 134, -76, -77,
	134, 136, -91, 134, 136, -91, 62, -11, 134, 134,
	-29, 55, 54, 33, -27, -23, 27, 134, 134, -75,
	-73, -74, -83, 134, 58, -13, -27, 134, 134, -14,
	72, 123, -30, 134, -27,
}

var plpgsqlDef = [...]int16{
	180, -2, 2, 6, 0, 1, 3, 0, 8, 0,
	188, 189, 190, 191, 192, 193, 194, 195, 196, 197,
	198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
	208, 209, 210, 211, 212, 213, 214, 215, 216, 217,
	218, 219, 220, 221, 222, 223, 224, 225, 226, 227,
	228, 229, 230, 231, 232, 233, 234, 235, 236, 237,
	238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
	248, 249, 250, 251, 252, 253, 254, 255, 256, 257,
	258, 259, 260, 261, 262, 263, 264, 265, 266, 267,
	268, 269, 270, 271, 272, 273, 274, 45, 5, 7,
	10, 11, 12, -2, 29, 30, 181, -2, 9, 33,
	0, 0, 32, 0, 18, 0, 46, 0, 0, 48,
	49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
	59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
	69, 70, 71, 72, 152, 177, 92, 0, 184, 184,
	111, 0, 0, 124, 145, 147, 153, 176, 175, 175,
	78, 0, 157, 158, 0, 0, 165, 165, 0, 148,
	149, 150, 151, 34, 0, 21, 17, 184, 167, 169,
	0, 47, 175, 43, 44, 0, 0, 45, 178, 0,
	0, 0, 185, 0, 0, 109, 110, 113, 0, 118,
	119, 120, 121, 122, 123, 0, 0, 0, 0, 0,
	79, 80, 16, 0, 160, 0, 0, 0, 0, 37,
	0, 0, 27, 28, 0, 20, 4, 168, 0, 172,
	173, 265, 0, 45, 96, 94, 177, 184, -2, 0,
	45, 0, 102, 104, 106, 186, 175, 107, 108, 140,
	126, 0, 0, 144, 73, 74, 75, 0, 154, 0,
	159, 161, 163, 0, 162, -2, 0, 0, 35, 36,
	14, 176, 25, 26, 45, 0, 174, 76, -2, 0,
	93, 45, 0, 0, 0, 45, 100, 101, 0, 0,
	0, 126, 139, 141, 143, 0, 0, 126, 0, 128,
	0, 130, 131, 132, 133, 134, 135, 136, 137, 138,
	0, 82, 0, 176, 164, 13, 39, 0, 41, 42,
	38, 15, 0, -2, 171, 89, 0, -2, 45, 98,
	146, 184, 0, 105, 187, 0, 142, 115, 125, 0,
	117, 0, 129, 77, 0, 0, 155, 0, 40, 19,
	0, 177, 45, 0, -2, 0, 178, 114, 116, 127,
	81, 83, 84, 156, 0, 0, -2, 91, 99, 45,
	0, 45, 103, 86, -2,
}

var plpgsqlTok1 = [...]uint8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	135, 3, 3, 3, 136, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 134,
	3, 137,
}

var plpgsqlTok2 = [...]uint8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
	122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
	132, 133,
}

var plpgsqlTok3 = [...]int8{
	0,
}

var plpgsqlErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	plpgsqlDebug        = 0
	plpgsqlErrorVerbose = false
)

type plpgsqlLexer interface {
	Lex(lval *plpgsqlSymType) int
	Error(s string)
}

type plpgsqlParser interface {
	Parse(plpgsqlLexer) int
	Lookahead() int
}

type plpgsqlParserImpl struct {
	lval  plpgsqlSymType
	stack [plpgsqlInitialStackSize]plpgsqlSymType
	char  int
}

func (p *plpgsqlParserImpl) Lookahead() int {
	return p.char
}

func plpgsqlNewParser() plpgsqlParser {
	return &plpgsqlParserImpl{}
}

const plpgsqlFlag = -1000

func plpgsqlTokname(c int) string {
	if c >= 1 && c-1 < len(plpgsqlToknames) {
		if plpgsqlToknames[c-1] != "" {
			return plpgsqlToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func plpgsqlStatname(s int) string {
	if s >= 0 && s < len(plpgsqlStatenames) {
		if plpgsqlStatenames[s] != "" {
			return plpgsqlStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func plpgsqlErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !plpgsqlErrorVerbose {
		return "syntax error"
	}

	for _, e := range plpgsqlErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + plpgsqlTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(plpgsqlPact[state])
	for tok := TOKSTART; tok-1 < len(plpgsqlToknames); tok++ {
		if n := base + tok; n >= 0 && n < plpgsqlLast && int(plpgsqlChk[int(plpgsqlAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if plpgsqlDef[state] == -2 {
		i := 0
		for plpgsqlExca[i] != -1 || int(plpgsqlExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; plpgsqlExca[i] >= 0; i += 2 {
			tok := int(plpgsqlExca[i])
			if tok < TOKSTART || plpgsqlExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if plpgsqlExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += plpgsqlTokname(tok)
	}
	return res
}

func plpgsqllex1(lex plpgsqlLexer, lval *plpgsqlSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(plpgsqlTok1[0])
		goto out
	}
	if char < len(plpgsqlTok1) {
		token = int(plpgsqlTok1[char])
		goto out
	}
	if char >= plpgsqlPrivate {
		if char < plpgsqlPrivate+len(plpgsqlTok2) {
			token = int(plpgsqlTok2[char-plpgsqlPrivate])
			goto out
		}
	}
	for i := 0; i < len(plpgsqlTok3); i += 2 {
		token = int(plpgsqlTok3[i+0])
		if token == char {
			token = int(plpgsqlTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(plpgsqlTok2[1]) /* unknown char */
	}
	if plpgsqlDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", plpgsqlTokname(token), uint(char))
	}
	return char, token
}

func plpgsqlParse(plpgsqllex plpgsqlLexer) int {
	return plpgsqlNewParser().Parse(plpgsqllex)
}

func (plpgsqlrcvr *plpgsqlParserImpl) Parse(plpgsqllex plpgsqlLexer) int {
	var plpgsqln int
	var plpgsqlVAL plpgsqlSymType
	var plpgsqlDollar []plpgsqlSymType
	_ = plpgsqlDollar // silence set and not used
	plpgsqlS := plpgsqlrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	plpgsqlstate := 0
	plpgsqlrcvr.char = -1
	plpgsqltoken := -1 // plpgsqlrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		plpgsqlstate = -1
		plpgsqlrcvr.char = -1
		plpgsqltoken = -1
	}()
	plpgsqlp := -1
	goto plpgsqlstack

ret0:
	return 0

ret1:
	return 1

plpgsqlstack:
	/* put a state and value onto the stack */
	if plpgsqlDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", plpgsqlTokname(plpgsqltoken), plpgsqlStatname(plpgsqlstate))
	}

	plpgsqlp++
	if plpgsqlp >= len(plpgsqlS) {
		nyys := make([]plpgsqlSymType, len(plpgsqlS)*2)
		copy(nyys, plpgsqlS)
		plpgsqlS = nyys
	}
	plpgsqlS[plpgsqlp] = plpgsqlVAL
	plpgsqlS[plpgsqlp].yys = plpgsqlstate

plpgsqlnewstate:
	plpgsqln = int(plpgsqlPact[plpgsqlstate])
	if plpgsqln <= plpgsqlFlag {
		goto plpgsqldefault /* simple state */
	}
	if plpgsqlrcvr.char < 0 {
		plpgsqlrcvr.char, plpgsqltoken = plpgsqllex1(plpgsqllex, &plpgsqlrcvr.lval)
	}
	plpgsqln += plpgsqltoken
	if plpgsqln < 0 || plpgsqln >= plpgsqlLast {
		goto plpgsqldefault
	}
	plpgsqln = int(plpgsqlAct[plpgsqln])
	if int(plpgsqlChk[plpgsqln]) == plpgsqltoken { /* valid shift */
		plpgsqlrcvr.char = -1
		plpgsqltoken = -1
		plpgsqlVAL = plpgsqlrcvr.lval
		plpgsqlstate = plpgsqln
		if Errflag > 0 {
			Errflag--
		}
		goto plpgsqlstack
	}

plpgsqldefault:
	/* default state action */
	plpgsqln = int(plpgsqlDef[plpgsqlstate])
	if plpgsqln == -2 {
		if plpgsqlrcvr.char < 0 {
			plpgsqlrcvr.char, plpgsqltoken = plpgsqllex1(plpgsqllex, &plpgsqlrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if plpgsqlExca[xi+0] == -1 && int(plpgsqlExca[xi+1]) == plpgsqlstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			plpgsqln = int(plpgsqlExca[xi+0])
			if plpgsqln < 0 || plpgsqln == plpgsqltoken {
				break
			}
		}
		plpgsqln = int(plpgsqlExca[xi+1])
		if plpgsqln < 0 {
			goto ret0
		}
	}
	if plpgsqln == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			plpgsqllex.Error(plpgsqlErrorMessage(plpgsqlstate, plpgsqltoken))
			Nerrs++
			if plpgsqlDebug >= 1 {
				__yyfmt__.Printf("%s", plpgsqlStatname(plpgsqlstate))
				__yyfmt__.Printf(" saw %s\n", plpgsqlTokname(plpgsqltoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for plpgsqlp >= 0 {
				plpgsqln = int(plpgsqlPact[plpgsqlS[plpgsqlp].yys]) + plpgsqlErrCode
				if plpgsqln >= 0 && plpgsqln < plpgsqlLast {
					plpgsqlstate = int(plpgsqlAct[plpgsqln]) /* simulate a shift of "error" */
					if int(plpgsqlChk[plpgsqlstate]) == plpgsqlErrCode {
						goto plpgsqlstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if plpgsqlDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", plpgsqlS[plpgsqlp].yys)
				}
				plpgsqlp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if plpgsqlDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", plpgsqlTokname(plpgsqltoken))
			}
			if plpgsqltoken == plpgsqlEofCode {
				goto ret1
			}
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			goto plpgsqlnewstate /* try again in the same state */
		}
	}

	/* reduction by production plpgsqln */
	if plpgsqlDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", plpgsqln, plpgsqlStatname(plpgsqlstate))
	}

	plpgsqlnt := plpgsqln
	plpgsqlpt := plpgsqlp
	_ = plpgsqlpt // guard against "declared and not used"

	plpgsqlp -= int(plpgsqlR2[plpgsqln])
	// plpgsqlp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if plpgsqlp+1 >= len(plpgsqlS) {
		nyys := make([]plpgsqlSymType, len(plpgsqlS)*2)
		copy(nyys, plpgsqlS)
		plpgsqlS = nyys
	}
	plpgsqlVAL = plpgsqlS[plpgsqlp+1]

	/* consult goto table to find next state */
	plpgsqln = int(plpgsqlR1[plpgsqln])
	plpgsqlg := int(plpgsqlPgo[plpgsqln])
	plpgsqlj := plpgsqlg + plpgsqlS[plpgsqlp].yys + 1

	if plpgsqlj >= plpgsqlLast {
		plpgsqlstate = int(plpgsqlAct[plpgsqlg])
	} else {
		plpgsqlstate = int(plpgsqlAct[plpgsqlj])
		if int(plpgsqlChk[plpgsqlstate]) != -plpgsqln {
			plpgsqlstate = int(plpgsqlAct[plpgsqlg])
		}
	}
	// dummy call; replaced with literal code
	switch plpgsqlnt {

	case 1:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:378
		{
			plpgsqllex.(*lexer).SetStmt(plpgsqlDollar[1].union.statement())
		}
	case 4:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-7 : plpgsqlpt+1]
//line plpgsql-gen.y:387
		{
			blockLabel, blockEndLabel := plpgsqlDollar[1].str, plpgsqlDollar[7].str
			if err := checkLoopLabels(blockLabel, blockEndLabel); err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.union.val = &plpgsqltree.Block{
				Label:      plpgsqlDollar[1].str,
				Decls:      plpgsqlDollar[2].union.statements(),
				Body:       plpgsqlDollar[4].union.statements(),
				Exceptions: plpgsqlDollar[5].union.exceptions(),
			}
		}
	case 5:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:402
		{
			plpgsqlVAL.union.val = plpgsqlDollar[2].union.statements()
		}
	case 6:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:406
		{

			plpgsqlVAL.union.val = []plpgsqltree.Statement(nil)
		}
	case 7:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:413
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statements()
		}
	case 8:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:417
		{
			plpgsqlVAL.union.val = []plpgsqltree.Statement{}
		}
	case 9:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:423
		{
			decs := plpgsqlDollar[1].union.statements()
			dec := plpgsqlDollar[2].union.statement()
			plpgsqlVAL.union.val = append(decs, dec)
		}
	case 10:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:429
		{
			dec := plpgsqlDollar[1].union.statement()
			plpgsqlVAL.union.val = []plpgsqltree.Statement{dec}
		}
	case 11:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:436
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 12:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:440
		{

			plpgsqlVAL.union.val = (plpgsqltree.Statement)(nil)
		}
	case 13:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-6 : plpgsqlpt+1]
//line plpgsql-gen.y:453
		{
			plpgsqlVAL.union.val = &plpgsqltree.Declaration{
				Var:      plpgsqltree.Variable(plpgsqlDollar[1].str),
				Constant: plpgsqlDollar[2].union.bool(),
				Typ:      plpgsqlDollar[3].union.typ(),
				Collate:  plpgsqlDollar[4].str,
				NotNull:  plpgsqlDollar[5].union.bool(),
				Expr:     plpgsqlDollar[6].union.expr(),
			}
		}
	case 14:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-5 : plpgsqlpt+1]
//line plpgsql-gen.y:464
		{
			return unimplemented(plpgsqllex, "alias for")
		}
	case 15:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-6 : plpgsqlpt+1]
//line plpgsql-gen.y:468
		{
			plpgsqlVAL.union.val = &plpgsqltree.CursorDeclaration{
				Name:   plpgsqltree.Variable(plpgsqlDollar[1].str),
				Scroll: plpgsqlDollar[2].union.cursorScrollOption(),
				Query:  plpgsqlDollar[6].union.sqlStatement(),
			}
		}
	case 16:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:478
		{
			plpgsqlVAL.union.val = tree.UnspecifiedScroll
		}
	case 17:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:482
		{
			plpgsqlVAL.union.val = tree.NoScroll
		}
	case 18:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:486
		{
			plpgsqlVAL.union.val = tree.Scroll
		}
	case 19:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:492
		{
			stmts, err := parser.Parse(plpgsqlDollar[1].str)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			if len(stmts) != 1 {
				return setErr(plpgsqllex, errors.New("expected exactly one SQL statement for cursor"))
			}
			plpgsqlVAL.union.val = stmts[0].AST
		}
	case 20:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:505
		{
			return unimplemented(plpgsqllex, "cursor arguments")
		}
	case 21:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:509
		{
		}
	case 22:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:514
		{
		}
	case 23:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:517
		{
		}
	case 24:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:522
		{
		}
	case 27:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:531
		{
		}
	case 28:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:534
		{
		}
	case 31:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:543
		{
			plpgsqlVAL.union.val = false
		}
	case 32:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:547
		{
			plpgsqlVAL.union.val = true
		}
	case 33:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:553
		{

			sqlStr, _, err := plpgsqllex.(*lexer).ReadSqlExpr(
				';', COLLATE, NOT, '=', COLON_EQUALS, DECLARE,
			)
			if err != nil {
				return setErr(plpgsqllex, err)
			}

			castExpr, err := plpgsqllex.(*lexer).ParseExpr("1::" + sqlStr)
			if err != nil {
				return setErr(plpgsqllex, errors.New("unable to parse type of variable declaration"))
			}
			switch t := castExpr.(type) {
			case *tree.CollateExpr:
				plpgsqlVAL.union.val = types.MakeCollatedString(types.String, t.Locale)
			case *tree.CastExpr:
				plpgsqlVAL.union.val = t.Type
			default:
				err := errors.New("unable to parse type of variable declaration")
				if strings.Contains(sqlStr, "%") {
					err = errors.WithIssueLink(errors.WithHint(err,
						"you may have attempted to use %TYPE or %ROWTYPE syntax, which is unsupported.",
					), errors.IssueLink{IssueURL: build.MakeIssueURL(114676)})
				}
				return setErr(plpgsqllex, err)
			}
		}
	case 34:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:586
		{
			plpgsqlVAL.str = ""
		}
	case 35:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:590
		{
			plpgsqlVAL.str = plpgsqlDollar[2].str
		}
	case 36:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:594
		{
			plpgsqlVAL.str = plpgsqlDollar[2].str
		}
	case 37:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:600
		{
			plpgsqlVAL.union.val = false
		}
	case 38:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:604
		{
			plpgsqlVAL.union.val = true
		}
	case 39:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:610
		{
			plpgsqlVAL.union.val = (plpgsqltree.Expr)(nil)
		}
	case 40:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:614
		{
			expr, err := plpgsqllex.(*lexer).ParseExpr(plpgsqlDollar[1].str)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.union.val = expr
		}
	case 41:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:624
		{
			sqlStr, _, err := plpgsqllex.(*lexer).ReadSqlExpr(';')
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.str = sqlStr
		}
	case 42:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:632
		{
			sqlStr, _, err := plpgsqllex.(*lexer).ReadSqlExpr(';')
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.str = sqlStr
		}
	case 45:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:651
		{
			plpgsqlVAL.union.val = []plpgsqltree.Statement{}
		}
	case 46:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:655
		{
			stmts := plpgsqlDollar[1].union.statements()
			stmts = append(stmts, plpgsqlDollar[2].union.statement())
			plpgsqlVAL.union.val = stmts
		}
	case 47:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:663
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.block()
		}
	case 48:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:667
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 49:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:671
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 50:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:675
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 51:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:679
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 52:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:683
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 53:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:687
		{
		}
	case 54:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:689
		{
		}
	case 55:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:691
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 56:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:695
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 57:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:699
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 58:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:703
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 59:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:707
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 60:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:711
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 61:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:715
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 62:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:719
		{
		}
	case 63:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:721
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 64:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:725
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 65:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:729
		{
		}
	case 66:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:731
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 67:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:735
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 68:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:739
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 69:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:743
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 70:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:747
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 71:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:751
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 72:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:755
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statement()
		}
	case 73:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:761
		{
			return unimplemented(plpgsqllex, "perform")
		}
	case 74:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:767
		{
			expr, err := plpgsqllex.(*lexer).ParseExpr(plpgsqlDollar[2].str)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			proc, ok := expr.(*tree.FuncExpr)
			if !ok {
				return setErr(plpgsqllex,
					errors.New("CALL statement target must be a stored procedure"),
				)
			}

			proc.InCall = true
			plpgsqlVAL.union.val = &plpgsqltree.Call{Proc: proc}
		}
	case 75:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:785
		{
			return unimplemented(plpgsqllex, "do")
		}
	case 76:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-4 : plpgsqlpt+1]
//line plpgsql-gen.y:791
		{
			expr, err := plpgsqllex.(*lexer).ParseExpr(plpgsqlDollar[3].str)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.union.val = &plpgsqltree.Assignment{
				Var:   plpgsqltree.Variable(plpgsqlDollar[1].str),
				Value: expr,
			}
		}
	case 77:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-5 : plpgsqlpt+1]
//line plpgsql-gen.y:804
		{
			plpgsqlVAL.union.val = &plpgsqltree.GetDiagnostics{
				IsStacked: plpgsqlDollar[2].union.bool(),
				DiagItems: plpgsqlDollar[4].union.getDiagnosticsItemList(),
			}

		}
	case 78:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:814
		{
			plpgsqlVAL.union.val = false
		}
	case 79:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:818
		{
			plpgsqlVAL.union.val = false
		}
	case 80:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:822
		{
			plpgsqlVAL.union.val = true
		}
	case 81:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:828
		{
			plpgsqlVAL.union.val = append(plpgsqlDollar[1].union.getDiagnosticsItemList(), plpgsqlDollar[3].union.getDiagnosticsItem())
		}
	case 82:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:832
		{
			plpgsqlVAL.union.val = plpgsqltree.GetDiagnosticsItemList{plpgsqlDollar[1].union.getDiagnosticsItem()}
		}
	case 83:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:838
		{
			plpgsqlVAL.union.val = &plpgsqltree.GetDiagnosticsItem{
				Kind:       plpgsqlDollar[3].union.getDiagnosticsKind(),
				TargetName: plpgsqlDollar[1].str,
			}
		}
	case 84:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:847
		{
			switch plpgsqlDollar[1].str {
			case "row_count":
				plpgsqlVAL.union.val = plpgsqltree.GetDiagnosticsRowCount
			case "pg_context":
				plpgsqlVAL.union.val = plpgsqltree.GetDiagnosticsContext
			case "pg_exception_detail":
				plpgsqlVAL.union.val = plpgsqltree.GetDiagnosticsErrorDetail
			case "pg_exception_hint":
				plpgsqlVAL.union.val = plpgsqltree.GetDiagnosticsErrorHint
			case "pg_exception_context":
				plpgsqlVAL.union.val = plpgsqltree.GetDiagnosticsErrorContext
			case "column_name":
				plpgsqlVAL.union.val = plpgsqltree.GetDiagnosticsColumnName
			case "constraint_name":
				plpgsqlVAL.union.val = plpgsqltree.GetDiagnosticsConstraintName
			case "pg_datatype_name":
				plpgsqlVAL.union.val = plpgsqltree.GetDiagnosticsDatatypeName
			case "message_text":
				plpgsqlVAL.union.val = plpgsqltree.GetDiagnosticsMessageText
			case "table_name":
				plpgsqlVAL.union.val = plpgsqltree.GetDiagnosticsTableName
			case "schema_name":
				plpgsqlVAL.union.val = plpgsqltree.GetDiagnosticsSchemaName
			case "returned_sqlstate":
				plpgsqlVAL.union.val = plpgsqltree.GetDiagnosticsReturnedSQLState
			default:

				return setErr(plpgsqllex, errors.Newf("unrecognized GET DIAGNOSTICS item: %s", redact.Safe(plpgsqlDollar[1].str)))
			}
		}
	case 85:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:883
		{
		}
	case 86:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-9 : plpgsqlpt+1]
//line plpgsql-gen.y:888
		{
			cond, err := plpgsqllex.(*lexer).ParseExpr(plpgsqlDollar[2].str)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.union.val = &plpgsqltree.If{
				Condition:  cond,
				ThenBody:   plpgsqlDollar[4].union.statements(),
				ElseIfList: plpgsqlDollar[5].union.elseIf(),
				ElseBody:   plpgsqlDollar[6].union.statements(),
			}
		}
	case 87:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:903
		{
			plpgsqlVAL.union.val = []plpgsqltree.ElseIf{}
		}
	case 88:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-5 : plpgsqlpt+1]
//line plpgsql-gen.y:907
		{
			cond, err := plpgsqllex.(*lexer).ParseExpr(plpgsqlDollar[3].str)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			newStmt := plpgsqltree.ElseIf{
				Condition: cond,
				Stmts:     plpgsqlDollar[5].union.statements(),
			}
			plpgsqlVAL.union.val = append(plpgsqlDollar[1].union.elseIf(), newStmt)
		}
	case 89:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:921
		{
			plpgsqlVAL.union.val = []plpgsqltree.Statement{}
		}
	case 90:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:925
		{
			plpgsqlVAL.union.val = plpgsqlDollar[2].union.statements()
		}
	case 91:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-7 : plpgsqlpt+1]
//line plpgsql-gen.y:931
		{
			expr := &plpgsqltree.Case{
				TestExpr:     plpgsqlDollar[2].str,
				CaseWhenList: plpgsqlDollar[3].union.caseWhens(),
			}
			if plpgsqlDollar[4].union.val != nil {
				expr.HaveElse = true
				expr.ElseStmts = plpgsqlDollar[4].union.statements()
			}
			plpgsqlVAL.union.val = expr
		}
	case 92:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:945
		{
			if plpgsqllex.(*lexer).Peek().id != WHEN {
				sqlStr, _, err := plpgsqllex.(*lexer).ReadSqlExpr(WHEN)
				if err != nil {
					return setErr(plpgsqllex, err)
				}
				plpgsqlVAL.str = sqlStr
			} else {
				plpgsqlVAL.str = ""
			}
		}
	case 93:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:959
		{
			stmts := plpgsqlDollar[1].union.caseWhens()
			stmts = append(stmts, plpgsqlDollar[2].union.caseWhen())
			plpgsqlVAL.union.val = stmts
		}
	case 94:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:965
		{
			stmts := []*plpgsqltree.CaseWhen{}
			stmts = append(stmts, plpgsqlDollar[1].union.caseWhen())
			plpgsqlVAL.union.val = stmts
		}
	case 95:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-4 : plpgsqlpt+1]
//line plpgsql-gen.y:973
		{
			expr := &plpgsqltree.CaseWhen{
				Expr:  plpgsqlDollar[2].str,
				Stmts: plpgsqlDollar[4].union.statements(),
			}
			plpgsqlVAL.union.val = expr
		}
	case 96:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:983
		{
			plpgsqlVAL.union.val = nil
		}
	case 97:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:987
		{
			plpgsqlVAL.union.val = plpgsqlDollar[2].union.statements()
		}
	case 98:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-5 : plpgsqlpt+1]
//line plpgsql-gen.y:993
		{
			loopLabel, loopEndLabel := plpgsqlDollar[1].str, plpgsqlDollar[4].str
			if err := checkLoopLabels(loopLabel, loopEndLabel); err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.union.val = &plpgsqltree.Loop{
				Label: plpgsqlDollar[1].str,
				Body:  plpgsqlDollar[3].union.statements(),
			}
		}
	case 99:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-7 : plpgsqlpt+1]
//line plpgsql-gen.y:1006
		{
			loopLabel, loopEndLabel := plpgsqlDollar[1].str, plpgsqlDollar[6].str
			if err := checkLoopLabels(loopLabel, loopEndLabel); err != nil {
				return setErr(plpgsqllex, err)
			}
			cond, err := plpgsqllex.(*lexer).ParseExpr(plpgsqlDollar[3].str)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.union.val = &plpgsqltree.While{
				Label:     plpgsqlDollar[1].str,
				Condition: cond,
				Body:      plpgsqlDollar[5].union.statements(),
			}
		}
	case 100:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-4 : plpgsqlpt+1]
//line plpgsql-gen.y:1024
		{
			return unimplemented(plpgsqllex, "for loop")
		}
	case 101:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:1031
		{
			return unimplemented(plpgsqllex, "for loop")
		}
	case 102:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1055
		{
			return unimplemented(plpgsqllex, "for loop")
		}
	case 103:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-8 : plpgsqlpt+1]
//line plpgsql-gen.y:1061
		{
			return unimplemented(plpgsqllex, "for each loop")
		}
	case 104:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1067
		{
		}
	case 105:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:1070
		{
		}
	case 106:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1075
		{
			plpgsqlVAL.union.val = &plpgsqltree.Exit{
				Label:     plpgsqlDollar[2].str,
				Condition: plpgsqlDollar[3].union.expr(),
			}
		}
	case 107:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1084
		{
			plpgsqlVAL.union.val = &plpgsqltree.Continue{
				Label:     plpgsqlDollar[2].str,
				Condition: plpgsqlDollar[3].union.expr(),
			}
		}
	case 108:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1093
		{
			var expr plpgsqltree.Expr
			if plpgsqlDollar[2].str != "" {
				var err error
				expr, err = plpgsqllex.(*lexer).ParseExpr(plpgsqlDollar[2].str)
				if err != nil {
					return setErr(plpgsqllex, err)
				}
			}
			plpgsqlVAL.union.val = &plpgsqltree.Return{Expr: expr}
		}
	case 109:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:1105
		{
			return unimplemented(plpgsqllex, "return next")
		}
	case 110:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:1109
		{
			return unimplemented(plpgsqllex, "return query")
		}
	case 111:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1115
		{
			sqlStr, err := plpgsqllex.(*lexer).ReadReturnExpr()
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.str = sqlStr
		}
	case 112:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1125
		{
			_, terminator, err := plpgsqllex.(*lexer).ReadSqlExpr(EXECUTE, ';')
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			if terminator == EXECUTE {
				return unimplemented(plpgsqllex, "return dynamic sql query")
			}
			_, _, err = plpgsqllex.(*lexer).ReadSqlExpr(';')
			if err != nil {
				return setErr(plpgsqllex, err)
			}
		}
	case 113:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:1142
		{
			return unimplemented(plpgsqllex, "empty RAISE statement")
		}
	case 114:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-6 : plpgsqlpt+1]
//line plpgsql-gen.y:1146
		{
			plpgsqlVAL.union.val = &plpgsqltree.Raise{
				LogLevel: plpgsqlDollar[2].str,
				Message:  plpgsqlDollar[3].str,
				Params:   plpgsqlDollar[4].union.exprs(),
				Options:  plpgsqlDollar[5].union.raiseOptions(),
			}
		}
	case 115:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-5 : plpgsqlpt+1]
//line plpgsql-gen.y:1155
		{
			plpgsqlVAL.union.val = &plpgsqltree.Raise{
				LogLevel: plpgsqlDollar[2].str,
				CodeName: plpgsqlDollar[3].str,
				Options:  plpgsqlDollar[4].union.raiseOptions(),
			}
		}
	case 116:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-6 : plpgsqlpt+1]
//line plpgsql-gen.y:1163
		{
			plpgsqlVAL.union.val = &plpgsqltree.Raise{
				LogLevel: plpgsqlDollar[2].str,
				Code:     plpgsqlDollar[4].str,
				Options:  plpgsqlDollar[5].union.raiseOptions(),
			}
		}
	case 117:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-5 : plpgsqlpt+1]
//line plpgsql-gen.y:1171
		{
			plpgsqlVAL.union.val = &plpgsqltree.Raise{
				LogLevel: plpgsqlDollar[2].str,
				Options:  plpgsqlDollar[4].union.raiseOptions(),
			}
		}
	case 124:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1187
		{
			plpgsqlVAL.str = ""
		}
	case 125:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:1194
		{
			plpgsqlVAL.union.val = plpgsqlDollar[2].union.raiseOptions()
		}
	case 126:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1198
		{
			plpgsqlVAL.union.val = []plpgsqltree.RaiseOption{}
		}
	case 127:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1205
		{
			option := plpgsqlDollar[3].union.raiseOption()
			plpgsqlVAL.union.val = append(plpgsqlDollar[1].union.raiseOptions(), *option)
		}
	case 128:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1210
		{
			option := plpgsqlDollar[1].union.raiseOption()
			plpgsqlVAL.union.val = []plpgsqltree.RaiseOption{*option}
		}
	case 129:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:1218
		{

			sqlStr, _, err := plpgsqllex.(*lexer).ReadSqlExpr(',', ';')
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			optionExpr, err := plpgsqllex.(*lexer).ParseExpr(sqlStr)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.union.val = &plpgsqltree.RaiseOption{
				OptType: plpgsqlDollar[1].str,
				Expr:    optionExpr,
			}
		}
	case 139:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1249
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.exprs()
		}
	case 140:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1253
		{
			plpgsqlVAL.union.val = []plpgsqltree.Expr{}
		}
	case 141:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1260
		{
			plpgsqlVAL.union.val = []plpgsqltree.Expr{plpgsqlDollar[1].union.expr()}
		}
	case 142:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:1264
		{
			plpgsqlVAL.union.val = append(plpgsqlDollar[1].union.exprs(), plpgsqlDollar[2].union.expr())
		}
	case 143:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1270
		{

			sqlStr, _, err := plpgsqllex.(*lexer).ReadSqlExpr(',', ';', USING)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			param, err := plpgsqllex.(*lexer).ParseExpr(sqlStr)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.union.val = param
		}
	case 144:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1285
		{
			plpgsqlVAL.union.val = &plpgsqltree.Assert{}
		}
	case 145:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1291
		{
			_, terminator, err := plpgsqllex.(*lexer).ReadSqlExpr(',', ';')
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			if terminator == ',' {
				_, _, err = plpgsqllex.(*lexer).ReadSqlExpr(';')
				if err != nil {
					return setErr(plpgsqllex, err)
				}
			}
		}
	case 146:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1306
		{
			plpgsqlVAL.union.val = plpgsqlDollar[1].union.statements()
		}
	case 147:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1312
		{
			stmt, err := plpgsqllex.(*lexer).MakeExecSqlStmt()
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.union.val = stmt
		}
	case 153:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1330
		{
			stmt, err := plpgsqllex.(*lexer).MakeDynamicExecuteStmt()
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.union.val = stmt
		}
	case 154:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1340
		{
			plpgsqlVAL.union.val = &plpgsqltree.Open{CurVar: plpgsqltree.Variable(plpgsqlDollar[2].str)}
		}
	case 155:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-5 : plpgsqlpt+1]
//line plpgsql-gen.y:1344
		{
			return unimplemented(plpgsqllex, "cursor for execute")
		}
	case 156:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-6 : plpgsqlpt+1]
//line plpgsql-gen.y:1348
		{
			stmts, err := parser.Parse(plpgsqlDollar[5].str)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			if len(stmts) != 1 {
				return setErr(plpgsqllex, errors.New("expected exactly one SQL statement for cursor"))
			}
			plpgsqlVAL.union.val = &plpgsqltree.Open{
				CurVar: plpgsqltree.Variable(plpgsqlDollar[2].str),
				Scroll: plpgsqlDollar[3].union.cursorScrollOption(),
				Query:  stmts[0].AST,
			}
		}
	case 157:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1365
		{
			fetch, err := plpgsqllex.(*lexer).MakeFetchOrMoveStmt(false)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.union.val = fetch
		}
	case 158:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1375
		{
			move, err := plpgsqllex.(*lexer).MakeFetchOrMoveStmt(true)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.union.val = move
		}
	case 159:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1385
		{
			plpgsqlVAL.union.val = &plpgsqltree.Close{CurVar: plpgsqltree.Variable(plpgsqlDollar[2].str)}
		}
	case 160:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:1391
		{
			plpgsqlVAL.union.val = &plpgsqltree.Null{}
		}
	case 161:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1397
		{
			plpgsqlVAL.union.val = &plpgsqltree.TransactionControl{Chain: plpgsqlDollar[2].union.bool()}
		}
	case 162:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1403
		{
			plpgsqlVAL.union.val = &plpgsqltree.TransactionControl{Chain: plpgsqlDollar[2].union.bool(), Rollback: true}
		}
	case 163:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:1410
		{
			plpgsqlVAL.union.val = true
		}
	case 164:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1414
		{
			plpgsqlVAL.union.val = false
		}
	case 165:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1418
		{
			plpgsqlVAL.union.val = false
		}
	case 166:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1423
		{
			plpgsqlVAL.union.val = []plpgsqltree.Exception(nil)
		}
	case 167:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:1427
		{
			plpgsqlVAL.union.val = plpgsqlDollar[2].union.exceptions()
		}
	case 168:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:1433
		{
			e := plpgsqlDollar[2].union.exception()
			plpgsqlVAL.union.val = append(plpgsqlDollar[1].union.exceptions(), *e)
		}
	case 169:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1438
		{
			e := plpgsqlDollar[1].union.exception()
			plpgsqlVAL.union.val = []plpgsqltree.Exception{*e}
		}
	case 170:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-4 : plpgsqlpt+1]
//line plpgsql-gen.y:1445
		{
			plpgsqlVAL.union.val = &plpgsqltree.Exception{
				Conditions: plpgsqlDollar[2].union.conditions(),
				Action:     plpgsqlDollar[4].union.statements(),
			}
		}
	case 171:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1454
		{
			c := plpgsqlDollar[3].union.condition()
			plpgsqlVAL.union.val = append(plpgsqlDollar[1].union.conditions(), *c)
		}
	case 172:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1459
		{
			c := plpgsqlDollar[1].union.condition()
			plpgsqlVAL.union.val = []plpgsqltree.Condition{*c}
		}
	case 173:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1466
		{
			plpgsqlVAL.union.val = &plpgsqltree.Condition{SqlErrName: plpgsqlDollar[1].str}
		}
	case 174:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql-gen.y:1470
		{
			plpgsqlVAL.union.val = &plpgsqltree.Condition{SqlErrState: plpgsqlDollar[2].str}
		}
	case 175:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1476
		{
			sqlStr, _, err := plpgsqllex.(*lexer).ReadSqlExpr(';')
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.str = sqlStr
		}
	case 176:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1486
		{
			sqlStr, _, err := plpgsqllex.(*lexer).ReadSqlStatement(';')
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.str = sqlStr
		}
	case 177:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1496
		{
			sqlStr, _, err := plpgsqllex.(*lexer).ReadSqlExpr(THEN)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.str = sqlStr
		}
	case 178:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1506
		{
			sqlStr, _, err := plpgsqllex.(*lexer).ReadSqlExpr(LOOP)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.str = sqlStr
		}
	case 179:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1516
		{
			sqlStr, _, err := plpgsqllex.(*lexer).ReadSqlExpr(')')
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.str = sqlStr
		}
	case 180:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1526
		{
			plpgsqlVAL.str = ""
		}
	case 181:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1530
		{
			plpgsqlVAL.str = plpgsqlDollar[2].str
		}
	case 182:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1536
		{
			plpgsqlVAL.str = ""
		}
	case 183:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1540
		{
			plpgsqlVAL.str = plpgsqlDollar[2].str
		}
	case 184:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql-gen.y:1546
		{
			plpgsqlVAL.str = ""
		}
	case 185:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1550
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	case 186:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql-gen.y:1556
		{
		}
	case 187:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql-gen.y:1558
		{
			expr, err := plpgsqllex.(*lexer).ParseExpr(plpgsqlDollar[2].str)
			if err != nil {
				return setErr(plpgsqllex, err)
			}
			plpgsqlVAL.union.val = expr
		}
	}
	goto plpgsqlstack /* stack new state and value */
}
